-- supabase/migrations/0014_grand_final_reset.sql
-- Logical migration 0014 — the grand-final RESET as two ordered match rows (Story 4.4, AC1 + AC2 + AC3).
--
-- ONE migration because it is ONE concern: making the grand final AD-21's "up to two ordered rows". 4.1
-- built the skeleton with a single terminal grand-final row (gf_order=1); 4.3 taught advance_match to crown
-- a champion at that terminal edgeless row. This slice adds the SECOND row (gf_order=2, the reset) and the
-- ONE conditional in double-elimination: side A of gf_order=1 is ALWAYS the Winners champion (0 losses); if
-- THEY win game 1 they are champion outright and there is no reset. Side B is the Losers survivor (1 loss);
-- only THEIR win forces the reset, because it hands the WB champion their first loss.
--
-- ⭐ WHY TWO ROWS AND NOT AN OVERWRITE (AD-21, closing adversarial hole H4). Without the reset row, a bracket
-- reset would write ONE grand-final destination slot TWICE with different winners (game-1 winner, then
-- game-2 winner) — and AD-8's `WHERE slot IS NULL OR = winner` guard (match_place_competitor) is built
-- precisely to REJECT a second different winner into a filled slot; it cannot tell a legitimate reset from a
-- double-route bug. AD-21 dissolves the dilemma: the reset routes into a SEPARATE row, so the champion slot
-- is a different column on a different row across the two games and is never overwritten in place. AC3
-- ("AD-8 conditional advance applies per row") is then satisfied BY CONSTRUCTION — each GF row is advanced
-- by the same advance_match, independently.
--
-- SCOPE (whole deliverable — NO new columns; `match`/`tournament` already carry gf_order, final_match_id
-- and the coalesce(gf_order,0) slot-unique index):
--   (a) AC1 — WIDEN match_routing_complete's grand_final arm so gf_order=1 MAY carry the conditional reset
--       edges while gf_order=2 stays terminal. Drop-and-re-add; the winners/losers arms are untouched.
--   (b) AC1 — `create or replace generate_bracket(...)`: the SAME signature, and the ONLY change is the
--       skeleton count (2B-2 -> 2B-1, the reset row is always emitted).
--   (c) AC2/AC3 — `create or replace advance_match(...)`: the SAME signature, plus the AD-21 GF-1
--       conditional (side A wins -> crown, follow no edge; side B wins -> fall through to the reset), and
--       tournament.final_match_id set to "the last GF row played" when a champion is crowned (DECISION A).
--
-- OUT OF SCOPE — do NOT add here (each has an owning story):
--   * tournament.state / the ceremony transition -> Epic 6 (DECISION C). Crowning a champion is not the same
--     as starting the ceremony; registration_open -> … -> ceremony -> closed are AUDITED admin transitions.
--     4.4 sets final_match_id (which match is decisive) and leaves state to the admin transition.
--   * bye / forfeit / grace -> Story 4.5. Byes are IMPOSSIBLE in the grand final by construction (both
--     finalists are present), so no GF row is ever a `bye`/`void`.
--   * Aprobar / demo-derived score -> 4.6; rollback -> 4.7; manual score -> 4.8; command route -> 4.9.
--     Like 4.2/4.3, this story has NO production caller — it is a mechanism proven at the SQL layer +
--     live-QA; 4.5/4.6 call advance_match inside their own transactions.
--
-- ⚠ DEPLOY NOTE. The widened grand_final arm is strictly MORE PERMISSIVE than 0013's (it now accepts a
-- gf_order=1 row WITH the reset edges, and a gf_order=2 row, in addition to everything 0013 accepted), so
-- dropping and re-adding it cannot newly fail an existing row. BUT a database that already holds a bracket
-- generated by 0013 has only a single terminal gf_order=1 row and NO reset row — advancing it would crown at
-- gf_order=1 (the old behaviour), never a reset. As 0013's header already states, a deployed DB holding
-- bracket rows must CLEAR AND REGENERATE through generateBracket(), never SQL-backfill. Safe as of
-- 2026-07-14: the remote has never generated a bracket, and local `db reset` starts from an empty `match`.

-- ════════════════════════════════════════════════════════════════════════════
-- (a) AC1 — WIDEN the grand_final arm of match_routing_complete.
-- ════════════════════════════════════════════════════════════════════════════
-- ⚠ 0013 flagged this by name ("STORY 4.4 MUST WIDEN THE grand_final ARM … widen the arm, do not weaken the
-- CHECK"). The AD-21 reset row means gf_order=1 gains a CONDITIONAL winner edge (-> the reset). Keep the
-- winners/losers arms EXACTLY as 0013 wrote them; keep `else false` a fail-closed wall, not a catch-all
-- (0013:153-157 — a fourth bracket value must be born a brick, not inherit "no edges").
--
--   * gf_order=1 carries the two reset edges AS A PAIR, or NEITHER (a bare GF-1 row is still valid —
--     0010's fixture inserts one). BOTH-OR-NEITHER, never one: exactly like the winners arm (which requires
--     BOTH a winner and a loser edge), a half-edged GF-1 row is a brick — if side B wins, one finalist would
--     be dropped with nowhere to go and the reset would stall `declared` forever (0010 has NO DELETE grant).
--     When PRESENT the edges are the FIXED AD-21 target — winner -> the reset's side b, loser -> its side a
--     (both grand_final, slot 0, gf_order 2) — so a malformed GF-1 edge (one aimed at a winners slot, self-
--     looping at gf_order=1, the wrong side, or present on only ONE side) stays UNREPRESENTABLE rather than
--     raising at advance time on an already-committed bracket (the same argument the gf_order edge guard
--     makes, 0013:117). This is stricter than merely asserting the target gf_order: it mirrors the winners
--     arm's both-edges rigor and pins the side, so the constraint keeps its "makes a BRICK unrepresentable"
--     charter for the new arm too, not just the old ones.
--   * gf_order=2 is the terminal reset: NEITHER edge. Its winner is the champion, by 0013's edgeless rule.
alter table public.match drop constraint match_routing_complete;
alter table public.match add constraint match_routing_complete check (
  case bracket
    when 'winners'     then winner_to_bracket is not null and loser_to_bracket is not null
    when 'losers'      then winner_to_bracket is not null and loser_to_bracket is null
    when 'grand_final' then
      case gf_order
        when 1 then
          -- BOTH-OR-NEITHER, NULL-safe. `(x is null) = (y is null)` compares two booleans (never NULL), so a
          -- HALF-edged row evaluates to FALSE and is rejected — not to NULL, which a CHECK would PASS (the
          -- exact three-valued-logic trap the 4.3 review caught in the gf_order edge guard).
          (winner_to_bracket is null) = (loser_to_bracket is null)
          and (winner_to_bracket is null
               or (winner_to_bracket = 'grand_final' and winner_to_slot = 0
                   and winner_to_gf_order = 2 and winner_to_side = 'b'))
          and (loser_to_bracket is null
               or (loser_to_bracket = 'grand_final' and loser_to_slot = 0
                   and loser_to_gf_order = 2 and loser_to_side = 'a'))
        when 2 then winner_to_bracket is null and loser_to_bracket is null  -- terminal: its winner is champion
        else false  -- gf_order is pinned to (1,2) by match_gf_order_guard; anything else fails closed
      end
    else false  -- an unknown bracket has no defined routing truth. Fail closed; never guess.
  end
);

-- The 0013 column comments said the edges are "NULL only on the grand-final row" / "NULL on the grand-final
-- row" — that is now true only of gf_order=2 (the reset). Correct them so the next reader is not misled.
comment on column public.match.winner_to_bracket is
  'Routing edge (D1): where this match''s WINNER goes, as the structural key (bracket, bracket_slot, gf_order) + side. Resolved through match_slot_uniq. NULL on the RESET grand-final row (gf_order=2), whose winner is the champion; on gf_order=1 it points at the reset (AD-21, Story 4.4). Emitted by lib/bracket/generate.ts — never re-derived in SQL.';
comment on column public.match.loser_to_bracket is
  'Routing edge (D1): where this match''s LOSER drops. NULL on a `losers` row — and that ABSENCE *is* two-loss elimination (FR-6, SOLUTION-DESIGN:359: "derived from bracket edges, never a stored flag"). NULL on the RESET grand-final row (gf_order=2, its loser is the runner-up); on gf_order=1 it points at the reset (AD-21).';

-- ════════════════════════════════════════════════════════════════════════════
-- (b) AC1 — generation emits the reset row: bump the skeleton count 2B-2 -> 2B-1.
-- ════════════════════════════════════════════════════════════════════════════
--
-- ⚠ `create or replace` with an IDENTICAL signature (bigint, text, jsonb, jsonb, jsonb) PRESERVES the
-- existing EXECUTE grants (0011:335-336, kept by 0013). This must NOT be a drop-and-recreate, and the grants
-- must NOT be re-issued. Everything below is 0013's function copied forward VERBATIM except the skeleton
-- count at step 5b: `2*B - 2` becomes `2*B - 1`, because the AD-21 reset row (gf_order=2) is ALWAYS emitted.
create or replace function public.generate_bracket(
  p_tournament_id   bigint,
  p_actor_steamid64 text,
  p_bracket_seed    jsonb,   -- the RAW draw (algorithm + permutation), recorded in the audit detail (AD-17)
  p_seeds           jsonb,   -- [{"roster_entry_id":123,"seed":1}, …] — the positions 1..N
  p_matches         jsonb    -- the COMPLETE skeleton: winners + losers + the two grand_final rows, WITH EDGES
) returns jsonb
  language plpgsql
  security invoker
  set search_path = ''
as $$
declare
  v_state       text;
  v_actual_ids  bigint[];
  v_claimed_ids bigint[];
  v_positions   int[];
  v_field       int;
  v_bracket     int;
  v_expected    int;
  v_matches     int;
begin
  -- 1. SERIALIZE on the tournament row. This lock is the spine of the whole story: it makes the state
  --    check + the roster re-read + every write one indivisible step, AND it is the lock the roster
  --    trigger's FOR KEY SHARE collides with (D3).
  select t.state
    into v_state
    from public.tournament t
   where t.id = p_tournament_id
     for update;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'bad_tournament');
  end if;

  -- 2. SINGLE-SHOT (D2). A second generate on a live bracket is REFUSED, never duplicated.
  if v_state = 'bracket_live' then
    return jsonb_build_object('ok', false, 'reason', 'already_live');
  end if;
  if v_state <> 'registration_closed' then
    return jsonb_build_object('ok', false, 'reason', 'not_closed', 'state', v_state);
  end if;

  -- 2b. A tournament still 'registration_closed' but ALREADY holding match rows is a corrupt state no
  --     legitimate path produces. Refuse cleanly rather than let step 7 abort on match_slot_uniq (23505).
  if exists (select 1 from public.match m where m.tournament_id = p_tournament_id) then
    return jsonb_build_object('ok', false, 'reason', 'already_live');
  end if;

  -- 3. OPTIMISTIC CONCURRENCY. Under the lock, assert the active roster is STILL exactly the set that was
  --    seeded. If an add/remove slipped in, the computed bracket is stale — refuse rather than commit it.
  select coalesce(array_agg(r.id order by r.id), '{}')
    into v_actual_ids
    from public.roster_entry r
   where r.tournament_id = p_tournament_id
     and r.status = 'active';

  select coalesce(array_agg((e->>'roster_entry_id')::bigint order by (e->>'roster_entry_id')::bigint), '{}')
    into v_claimed_ids
    from jsonb_array_elements(p_seeds) as e;

  if v_actual_ids is distinct from v_claimed_ids then
    return jsonb_build_object('ok', false, 'reason', 'roster_changed');
  end if;

  -- 4. FIELD BOUNDS (AC1). Only reachable by a DIRECT RPC call — which is why it is here: the DB is the
  --    authority, not the caller.
  v_field := coalesce(array_length(v_actual_ids, 1), 0);
  if v_field < 8 or v_field > 16 then
    return jsonb_build_object('ok', false, 'reason', 'bad_field_count', 'field_size', v_field);
  end if;

  -- 5. THE PAYLOAD IS NOT TRUSTED.
  --
  --    5a. p_seeds must be a PERMUTATION of 1..N. Step 3 compared only the id SET; the `seed` values are
  --        written straight into roster_entry.bracket_seed (no CHECK, no UNIQUE).
  select coalesce(array_agg((e->>'seed')::int order by (e->>'seed')::int), '{}')
    into v_positions
    from jsonb_array_elements(p_seeds) as e;

  if v_positions is distinct from (select array_agg(g order by g) from generate_series(1, v_field) as g) then
    return jsonb_build_object('ok', false, 'reason', 'bad_seeds');
  end if;

  --    5b. p_matches must be the COMPLETE skeleton: B-1 winners + B-2 losers + 2 grand-final = 2B-1 rows.
  --        The AD-21 reset row (gf_order=2) is ALWAYS emitted (Story 4.4), so the count is 2B-1, not 2B-2.
  --        Without this, `p_matches = '[]'` inserts nothing, step 8 still flips the state to 'bracket_live',
  --        step 9 still audits, and the function returns ok:true — leaving a live tournament with NO bracket
  --        and no DELETE grant on `match` to clean up. Unrecoverable.
  v_bracket := 8;
  while v_bracket < v_field loop
    v_bracket := v_bracket * 2;
  end loop;
  v_expected := 2 * v_bracket - 1;

  if jsonb_typeof(p_matches) <> 'array' or jsonb_array_length(p_matches) <> v_expected then
    return jsonb_build_object(
      'ok', false, 'reason', 'bad_skeleton',
      'expected', v_expected,
      'received', case when jsonb_typeof(p_matches) = 'array' then jsonb_array_length(p_matches) else null end
    );
  end if;

  -- ── Past this line everything writes, and it all commits or none of it does. ──

  -- 6. Record the draw: each active entry's seed POSITION 1..N (AC1).
  --    ⚠ ORDERING IS LOAD-BEARING: this UPDATE fires the D3 roster-lock trigger, which rejects roster
  --    writes once state='bracket_live'. It MUST run BEFORE step 8 flips the state.
  update public.roster_entry r
     set bracket_seed = s.seed
    from (
      select (e->>'roster_entry_id')::bigint as id,
             (e->>'seed')::int               as seed
        from jsonb_array_elements(p_seeds) as e
    ) s
   where r.id = s.id
     and r.tournament_id = p_tournament_id;

  -- ⭐ 6b. EVERY EDGE MUST POINT AT A ROW THE PAYLOAD ACTUALLY CONTAINS (4.3 code review).
  --    `match_routing_complete` proves an edge is DECLARED; it cannot prove it POINTS SOMEWHERE. There is
  --    no self-FK to lean on — generation INSERTs every row in ONE statement, so no row has an id yet when
  --    its neighbours are written (that is the whole reason the edges are structural, not match_ids).
  --
  --    This is UNCHANGED from 0013 and needs no change for the reset row: gf_order=1's new edge names
  --    (grand_final, 0, gf_order=2), and the resolution below already keys on
  --    (bracket, slot, coalesce(gf_order,0)), so it validates the reset target for free (0013:317-319
  --    anticipated exactly this — "the shape Story 4.4 will produce").
  if exists (
    with r as (
      select m ->> 'bracket'                        as bracket,
             (m ->> 'bracket_slot')::int            as slot,
             (m ->> 'gf_order')::int                as gf,
             m -> 'winner_to' ->> 'bracket'         as w_b,
             (m -> 'winner_to' ->> 'slot')::int     as w_s,
             (m -> 'winner_to' ->> 'gf_order')::int as w_g,
             m -> 'loser_to'  ->> 'bracket'         as l_b,
             (m -> 'loser_to' ->> 'slot')::int      as l_s,
             (m -> 'loser_to' ->> 'gf_order')::int  as l_g
        from jsonb_array_elements(p_matches) as m
    )
    select 1
      from r
     where (
             r.w_b is not null
             and not exists (
               select 1 from r t
                where t.bracket = r.w_b and t.slot = r.w_s
                  and coalesce(t.gf, 0) = coalesce(r.w_g, 0)
             )
           )
        or (
             r.l_b is not null
             and not exists (
               select 1 from r t
                where t.bracket = r.l_b and t.slot = r.l_s
                  and coalesce(t.gf, 0) = coalesce(r.l_g, 0)
             )
           )
  ) then
    return jsonb_build_object(
      'ok', false, 'reason', 'bad_skeleton',
      'detail', 'a routing edge names a (bracket, slot, gf_order) that no match in the payload occupies'
    );
  end if;

  -- 7. The bracket itself: every row at once, WITH its routing edges (D1). Unchanged from 0013 — the extra
  --    grand_final (reset) row flows through verbatim as one more element of p_matches.
  insert into public.match (
    tournament_id, bracket, bracket_position, bracket_slot, gf_order,
    competitor_a, competitor_b, winner_entry, state,
    winner_to_bracket, winner_to_slot, winner_to_gf_order, winner_to_side,
    loser_to_bracket,  loser_to_slot,  loser_to_gf_order,  loser_to_side
  )
  select
    p_tournament_id,
    m->>'bracket',
    m->>'bracket_position',
    (m->>'bracket_slot')::int,
    (m->>'gf_order')::int,
    (m->>'competitor_a')::bigint,
    (m->>'competitor_b')::bigint,
    (m->>'winner_entry')::bigint,
    m->>'state',
    m -> 'winner_to' ->> 'bracket',
    (m -> 'winner_to' ->> 'slot')::int,
    (m -> 'winner_to' ->> 'gf_order')::int,
    m -> 'winner_to' ->> 'side',
    m -> 'loser_to'  ->> 'bracket',
    (m -> 'loser_to' ->> 'slot')::int,
    (m -> 'loser_to' ->> 'gf_order')::int,
    m -> 'loser_to'  ->> 'side'
  from jsonb_array_elements(p_matches) as m;
  get diagnostics v_matches = row_count;

  -- Belt and braces: the count was validated on the way in, so a mismatch here is impossible without a
  -- Postgres bug. Assert it anyway — this is the row that flips a tournament live.
  if v_matches <> v_expected then
    raise exception 'generate_bracket: inserted % match rows, expected %', v_matches, v_expected;
  end if;

  -- 8. The state transition the whole story exists to make.
  update public.tournament
     set state = 'bracket_live'
   where id = p_tournament_id;

  -- 9. The audit row, INSIDE the transaction (AD-17).
  insert into public.audit_log (tournament_id, actor_steamid64, action, detail)
  values (
    p_tournament_id,
    p_actor_steamid64,
    'generate_bracket',
    jsonb_build_object(
      'before',       'registration_closed',
      'after',        'bracket_live',
      'field_size',   v_field,
      'bracket_size', v_bracket,
      'match_count',  v_matches,
      'bracket_seed', p_bracket_seed   -- the raw draw: algorithm + the full seed permutation
    )
  );

  return jsonb_build_object(
    'ok', true, 'field_size', v_field, 'bracket_size', v_bracket, 'match_count', v_matches
  );
end;
$$;

-- NO grants re-issued: `create or replace` with the same signature keeps 0011:335-336 intact.

-- ════════════════════════════════════════════════════════════════════════════
-- (c) AC2/AC3 — advance_match gains the AD-21 GF-1 conditional + final_match_id.
-- ════════════════════════════════════════════════════════════════════════════
--
-- ⚠ `create or replace` with the IDENTICAL signature (bigint, text, boolean) PRESERVES the 0013 grants
-- (0013:867-868). Everything below is 0013's function copied forward VERBATIM except:
--   * the source SELECT now also reads `bracket` and `gf_order` (needed by the conditional);
--   * the AD-21 GF-1 conditional, applied to the SOURCE before the cascade is planned;
--   * tournament.final_match_id is set when a champion is crowned (DECISION A).
-- The champion-detection, the edge loop, the void raise, the two-pass design, the canonical lock order and
-- the emit gate are all UNCHANGED — re-read 0013:512-858 alongside this.
--
-- ⭐ THE AD-21 CONDITIONAL, PRECISELY. gf_order=1's competitor_a is ALWAYS the Winners champion (side A,
-- 0 losses) and competitor_b the Losers survivor (side B, 1 loss) — a convention generation guarantees
-- (winnersWinnerTarget -> side a, losersWinnerTarget -> side b). So:
--   * winner_entry = competitor_a  -> side A won: they are UNDEFEATED -> champion outright, NO reset. Crown
--     them and follow NEITHER edge (skip the reset edges gf_order=1 carries).
--   * winner_entry = competitor_b  -> side B won: they handed A its first loss -> the reset fires. Fall
--     through unchanged; the normal edge loop routes the winner (B) to gf_order=2/side b and the loser (A)
--     to gf_order=2/side a. Because gf_order=2 is `declared` (not `bye`), the cascade stops there; a later
--     advance_match(gf_order=2) crowns the champion by the edgeless rule.
create or replace function public.advance_match(
  p_match_id        bigint,
  p_actor_steamid64 text,
  p_emit            boolean default true   -- AD-11: 4.6 folds the advance into its own single Broadcast
) returns jsonb
  language plpgsql
  security invoker
  set search_path = ''
as $$
declare
  v_m      record;
  v_src    record;
  v_dest   record;
  v_edge   record;
  v_task   jsonb;
  v_todo   jsonb := '[]'::jsonb;   -- queue of nodes to advance FROM: [{src, winner, loser}]
  v_plan   jsonb := '[]'::jsonb;   -- the validated, ordered placements: [{match_id, entry, side, walkover}]
  v_loser  bigint;
  v_occ    bigint;
  v_walk   boolean;
  v_champ  bigint;
  v_iter   int := 0;
  v_hops   int;
  v_tid    bigint;
begin
  -- ══ 1. WHICH BRACKET ARE WE IN? An UNLOCKED peek, and it learns exactly one thing: the tournament.
  --    It must not lock, because the very next statement takes every lock in canonical order and a lock
  --    acquired ahead of that one would be OUT of that order — which is the whole bug this replaced.
  --    (`match` has NO DELETE grant (0010:227), so a row cannot vanish between this read and the lock.)
  select m.tournament_id into v_tid from public.match m where m.id = p_match_id;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'bad_match');
  end if;

  -- ══ 1b. ⭐ EVERY LOCK, IN ONE STATEMENT, IN CANONICAL (id) ORDER. See the 0013 header: this is what makes
  --    a deadlock impossible BY CONSTRUCTION. Every advance in this tournament locks the same rows in the
  --    same order, so two of them can queue but can never form a cycle. ⚠ DO NOT reintroduce a `for update`
  --    that runs BEFORE this one (that was the 4.3 deadlock).
  perform 1
     from public.match m
    where m.tournament_id = v_tid
    order by m.id
      for update;

  -- ══ 1c. NOW read the source, under the lock. Its result and its edges cannot move under us.
  --    ⭐ Story 4.4 adds `bracket` and `gf_order`: the AD-21 GF-1 conditional below reads them.
  select m.id, m.tournament_id, m.state, m.winner_entry, m.competitor_a, m.competitor_b,
         m.bracket, m.gf_order
    into v_m
    from public.match m
   where m.id = p_match_id;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'bad_match');
  end if;

  -- ══ 2. AC2 — THE RESULT GATE. No result, no consequence.
  --    `void` falls here too (it can never be played: nothing arrives, nothing leaves), as do `declared`,
  --    `live`, `awaiting_grace`, `pending` and `rolled_back` — see 0013 for why `pending` matters most.
  if v_m.state not in ('bye', 'forfeit', 'resolved', 'manual_resolved') then
    return jsonb_build_object('ok', false, 'reason', 'not_resolved', 'state', v_m.state);
  end if;

  -- A result without a winner is not a result. (This is also what keeps an un-walked Losers `bye` node —
  -- state='bye', competitors still NULL — from "advancing" nobody into the next round.)
  if v_m.winner_entry is null then
    return jsonb_build_object('ok', false, 'reason', 'not_resolved', 'state', v_m.state);
  end if;

  -- ══ 3. D2 — THE LOSER. Not a column: the competitor who is not the winner. NULL for a bye (one
  --    competitor), non-NULL for a forfeit / resolved / manual_resolved. `match_winner_is_competitor`
  --    (0010:94-98) guarantees the winner really is one of the two, so this cannot pick a stranger.
  v_loser := case when v_m.competitor_a = v_m.winner_entry then v_m.competitor_b else v_m.competitor_a end;

  v_todo := jsonb_build_array(
    jsonb_build_object('src', v_m.id, 'winner', v_m.winner_entry, 'loser', v_loser)
  );

  -- ══ 3b. ⭐ AD-21 — THE GRAND FINAL'S FIRST ROW IS THE ONE CONDITIONAL EDGE IN DOUBLE-ELIM. Side A is the
  --    Winners champion (0 losses); if THEY win game 1 they are champion outright — no reset, follow no
  --    edge. Side B is the Losers survivor; only their win hands A its first loss and forces the reset
  --    (gf_order=2). This runs READ-ONLY, inside pass 1's scope, BEFORE the cascade is planned (0013's
  --    two-pass invariant is preserved — no lock is taken here). When side B wins, fall through unchanged
  --    and the normal edge loop routes both competitors into the reset row.
  if v_m.bracket = 'grand_final' and v_m.gf_order = 1 and v_m.winner_entry = v_m.competitor_a then
    v_champ := v_m.winner_entry;
    v_todo  := '[]'::jsonb;   -- crown, do NOT enqueue the (reset) edges
  end if;

  -- ══ 4. PASS 1 — PLAN THE WHOLE CASCADE, READ-ONLY. Any refusal here has written nothing.
  --    An explicit bounded worklist, never open recursion: a `while true` inside an admin transaction is
  --    an infinite loop, and the cap turns a routing cycle into a loud failure instead of a hang.
  while jsonb_array_length(v_todo) > 0 loop
    v_iter := v_iter + 1;
    if v_iter > 32 then
      -- Generous by an order of magnitude: a 16-bracket's longest walkover chain is under 10 hops.
      -- Getting here means the persisted edges contain a CYCLE, which generation cannot produce.
      raise exception
        'advance_match: hop cap exceeded advancing match % — the persisted routing edges contain a cycle',
        p_match_id;
    end if;

    v_task := v_todo -> 0;
    v_todo := v_todo - 0;

    select m2.winner_to_bracket, m2.winner_to_slot, m2.winner_to_gf_order, m2.winner_to_side,
           m2.loser_to_bracket,  m2.loser_to_slot,  m2.loser_to_gf_order,  m2.loser_to_side
      into v_src
      from public.match m2
     where m2.id = (v_task->>'src')::bigint;

    -- ⚠ A MISS HERE MUST NOT BE SILENT (4.3 code review). Every row in the worklist is one we already hold
    -- under the canonical lock, so this cannot miss — but if it ever did, v_src would be all-NULL, the
    -- champion test below would read `winner_to_bracket is null` as TRUE, and the function would CROWN THE
    -- ENTRY AS CHAMPION and return ok:true. That is the one place a silent miss turns into a POSITIVE,
    -- WRONG outcome, in a function that raises loudly on four other "impossible" conditions. Fail closed.
    if not found then
      raise exception
        'advance_match: worklist referenced match % but it no longer exists (tournament %)',
        (v_task->>'src')::bigint, v_tid;
    end if;

    -- NEVER A SILENT NO-OP (lib/roster.ts:180-182) — but the Grand Final is the ONE legitimate
    -- "advanced nobody": the terminal row (gf_order=2, and gf_order=1 when side A wins — handled above by
    -- the AD-21 conditional, which empties the worklist so we never reach here for it) has no outbound
    -- edge (match_routing_complete), so its winner is the CHAMPION. Checked HERE rather than at the source,
    -- so it covers both a direct advance of the reset row and a walkover that cascades INTO a terminal row.
    if v_src.winner_to_bracket is null then
      v_champ := (v_task->>'winner')::bigint;
    end if;

    -- Both edges of this node, uniformly. The winner always travels; the loser travels only if there IS
    -- one (NULL for a bye) and there is somewhere for them to go (a Losers loser is ELIMINATED — D2).
    for v_edge in
      select e.ord, e.kind, e.b, e.slot, e.gf, e.side, e.entry
        from (values
          (1, 'winner', v_src.winner_to_bracket, v_src.winner_to_slot, v_src.winner_to_gf_order,
              v_src.winner_to_side, (v_task->>'winner')::bigint),
          (2, 'loser',  v_src.loser_to_bracket,  v_src.loser_to_slot,  v_src.loser_to_gf_order,
              v_src.loser_to_side,  (v_task->>'loser')::bigint)
        ) as e(ord, kind, b, slot, gf, side, entry)
       where e.b is not null
         and e.entry is not null
       order by e.ord
    loop
      -- Resolve the structural edge to a row through match_slot_uniq (0010:112-113) — one indexed lookup.
      -- No FOR UPDATE here, and that is deliberate: step 1b already holds EVERY row of this tournament,
      -- taken in canonical id order, so this row is locked and the plan built here cannot go stale. Taking
      -- a lock at THIS point is what produced the Winners-Final/Losers-Final deadlock (0013 header).
      select d.id, d.state, d.winner_entry, d.competitor_a, d.competitor_b, d.winner_to_bracket
        into v_dest
        from public.match d
       where d.tournament_id            = v_m.tournament_id
         and d.bracket                  = v_edge.b
         and d.bracket_slot             = v_edge.slot
         and coalesce(d.gf_order, 0)    = coalesce(v_edge.gf, 0);

      if not found then
        -- match_routing_complete guarantees the edge EXISTS; it cannot guarantee it POINTS somewhere real.
        -- A dangling edge is a generation bug, and it is not something to paper over.
        raise exception
          'advance_match: match % has a %-edge to (%,%,%) but no such match row exists in tournament %',
          (v_task->>'src')::bigint, v_edge.kind, v_edge.b, v_edge.slot, v_edge.gf, v_m.tournament_id;
      end if;

      if v_dest.state = 'void' then
        -- IMPOSSIBLE BY CONSTRUCTION: a void node has ZERO possible arrivals (generate.ts — the
        -- `arrivals === 2 ? 'declared' : arrivals === 1 ? 'bye' : 'void'` propagation) — both of its
        -- feeders were byes, so neither ever produces a loser. Reaching one means the routing is
        -- broken. Raise; do not paper over it. (The AD-21 reset row is `declared`, never `void`.)
        raise exception
          'advance_match: match % routed a % into VOID node % — the bracket routing is broken',
          (v_task->>'src')::bigint, v_edge.kind, v_dest.id;
      end if;

      -- ⭐ AC1, evaluated as a READ (we hold the row's lock, so what we see is what pass 2 will write to).
      v_occ := case when v_edge.side = 'a' then v_dest.competitor_a else v_dest.competitor_b end;

      if v_occ is not null and v_occ <> v_edge.entry then
        -- A DIFFERENT player already holds this seat. Refuse — never overwrite. Nothing has been written.
        return jsonb_build_object(
          'ok', false, 'reason', 'slot_taken',
          'match_id', v_dest.id, 'side', v_edge.side, 'occupant', v_occ, 'entry', v_edge.entry
        );
      end if;

      -- ⭐ D3 — a `bye` destination is a WALKOVER: the arrival wins it unplayed.
      v_walk := (v_dest.state = 'bye');

      if v_walk and v_dest.winner_entry is not null and v_dest.winner_entry <> v_edge.entry then
        -- Unreachable in a well-formed bracket (a bye node has exactly one possible arrival, and the seat
        -- check above would already have caught a different occupant) — but a winner is a competitor, so
        -- if these ever disagree the row is corrupt. Fail closed rather than crown the wrong player.
        return jsonb_build_object(
          'ok', false, 'reason', 'slot_taken',
          'match_id', v_dest.id, 'side', v_edge.side, 'occupant', v_dest.winner_entry, 'entry', v_edge.entry
        );
      end if;

      v_plan := v_plan || jsonb_build_object(
        'match_id', v_dest.id,
        'entry',    v_edge.entry,
        'side',     v_edge.side,
        'walkover', v_walk
      );

      if v_walk then
        -- …and the advance CONTINUES from it. A walkover has no loser (nobody was beaten), so the chain
        -- carries only a winner. It ends at a `declared` node (which waits for its real opponent) or at
        -- a terminal grand-final row (whose winner is the champion — detected at the top of the loop).
        v_todo := v_todo || jsonb_build_object(
          'src', v_dest.id, 'winner', v_edge.entry, 'loser', null
        );
      end if;
    end loop;
  end loop;

  -- ── Past this line everything writes, and it all commits or none of it does. ──

  -- ══ 5. PASS 2 — APPLY. Every destination is already locked and already validated.
  v_hops := jsonb_array_length(v_plan);

  for v_task in select * from jsonb_array_elements(v_plan) loop
    if not public.match_place_competitor(
             (v_task->>'match_id')::bigint,
              v_task->>'side',
             (v_task->>'entry')::bigint,
             (v_task->>'walkover')::boolean
           ) then
      -- Impossible: pass 1 took FOR UPDATE on this exact row and found the seat free (or already ours).
      -- If the predicate fails now, the lock did not hold what we think it held — abort loudly.
      raise exception
        'advance_match: destination % side % was taken after validation — this should be unreachable under FOR UPDATE',
        (v_task->>'match_id')::bigint, v_task->>'side';
    end if;
  end loop;

  -- ══ 5b. ⭐ DECISION A — tournament.final_match_id = "the last GF row played". When a champion is crowned,
  --    p_match_id IS that row: gf_order=1's id when side A wins outright, gf_order=2's id when the reset
  --    resolves. AD-13's fair_seed = SHA-256(final demo) needs this to know which demo is championship-
  --    deciding (SOLUTION-DESIGN:64). service_role holds UPDATE on tournament (generate_bracket writes
  --    tournament.state under the same grant). It is set only on a crown, so a non-final advance leaves it
  --    untouched, and it is idempotent (a replay writes the same id).
  if v_champ is not null then
    update public.tournament
       set final_match_id = p_match_id
     where id = v_m.tournament_id;
  end if;

  -- ══ 6. D4 — THE AUDIT ROW, INSIDE THE TRANSACTION (AD-17). ONE row per CALL, not per hop: a bye
  --    cascade is a single admin consequence and reads as one. `action='advance'` needs NO migration —
  --    it is already the enumerated vocabulary (0003:25). `target_match_id` is the SOURCE match.
  --
  --    A REPLAY WRITES A SECOND ROW, DELIBERATELY. The audit is a log of admin ACTIONS, not of state
  --    deltas — and a silent second call is exactly the double-tap AD-8 worries about, so it is worth
  --    seeing. The bracket is unchanged either way; that is AC1's idempotency, and it is asserted.
  insert into public.audit_log (tournament_id, actor_steamid64, action, target_match_id, detail)
  values (
    v_m.tournament_id,
    p_actor_steamid64,
    'advance',
    p_match_id,
    jsonb_build_object(
      'winner_entry', v_m.winner_entry,
      'loser_entry',  v_loser,
      'hops',         v_plan,
      'champion',     v_champ
    )
  );

  -- ══ 7. AC3 — THE BROADCAST, POST-COMMIT BY CONSTRUCTION. Unchanged from 0013 — the reset champion sets
  --    v_champ exactly as the single GF row did, so the emit gate `v_hops > 0 or v_champ is not null`
  --    covers "champion crowned, zero hops" for BOTH gf_order=1 (side A wins) and gf_order=2 (the reset).
  --    ⚠ DO NOT "FIX" the error swallowing, and DO NOT build a second emitter (0013:821-830).
  if coalesce(p_emit, true) and (v_hops > 0 or v_champ is not null) then
    perform realtime.send(
      jsonb_build_object(
        'tournament_id', v_m.tournament_id,
        'match_id',      p_match_id,
        'winner_entry',  v_m.winner_entry,
        'loser_entry',   v_loser,
        'champion',      v_champ,
        'hops',          v_plan
      ),
      'bracket.advanced',
      'tournament:' || v_m.tournament_id::text,
      false
    );
  end if;

  return jsonb_build_object(
    'ok', true, 'advanced', v_hops, 'champion', v_champ, 'hops', v_plan
  );
end;
$$;

-- NO grants re-issued: `create or replace` with the same signature keeps 0013:867-868 intact.
