// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Read directly rather than through `env()`, which throws when it is unset: `prisma generate` runs in
    // every build and typecheck, and none of them has, or needs, a database (Story 3-5).
    url: process.env.DATABASE_URL,
  },
});
