-- supabase/tests/0013_advance_test.sql
-- pgTAP proof for migration 0013 (Story 4.3): the idempotent conditional advance.
-- Run via: supabase test db. Runs inside a transaction and rolls back — no data persists.
--
--   D1     the routing edges are PERSISTED, and match_routing_complete makes a BRICK unrepresentable  -> B
--   D1     generation actually emits them (through the REAL generate_bracket RPC)                     -> C
--   AC2    "consequence, not control": no RESULT, no advance — and a refusal writes NOTHING           -> D
--   AC1    the conditional write: the winner lands, a REPLAY is a no-op, both are success             -> E
--   D3     THE BYE CASCADE: a player arriving at a walkover is advanced STRAIGHT THROUGH it           -> F
--   D2     THE LOSER DROPS — and a Losers loser is ELIMINATED (proven by an ABSENCE)                  -> G
--   D4     the `advance` audit row, and EVERY key of its detail                                       -> H
--   AC3    the Broadcast — post-commit by construction, on the spine's channel + event                -> I
--   AC1    the DOUBLE-ROUTE IS REFUSED (`slot_taken`), and the refusal commits NOTHING AT ALL         -> J
--   —      the Grand Final's champion, and the Story-4.2 cross-story regression                       -> K
--   AC1    the PREDICATE itself, in isolation (the seat)                                              -> L
--   AC1    the PREDICATE must guard the WINNER too, not just the seat  (4.3 code review)              -> M
--
-- ⚠ F IS D3 AND G IS D2 — the legend used to say the reverse. D3 is asserted BEFORE D2 on purpose (see the
-- note on Section F), and the legend was never updated to match the reorder. It is now.
--
-- ⚠ EVERY FIXTURE BRACKET HERE IS GENERATED BY THE REAL `generate_bracket` RPC, from the REAL
-- `generateBracket()` payload (pg_temp.matches11 is a golden snapshot of its output for an 11-player
-- field — dumped, not hand-derived). That is deliberate and it is the 4.1 review's headline lesson: a
-- hand-written fixture that no longer resembles what the generator emits proves less than it claims. The
-- bye/void layout below is not invented — it is what an 11-player field STRUCTURALLY IS.
--
-- ⚠ THE 11-PLAYER FIELD IS THE POINT, NOT A CORNER CASE. bracketSize 16, 30 rows, seeds 1-5 draw byes,
-- and TEN of the rows are `bye`/`void`. A loser dropping into a `bye` node that is never walked through is
-- a Losers bracket that STALLS FOREVER — so Section G is the assertion this whole story exists for.
--
-- SQLSTATE: 23514 = a CHECK (incl. match_routing_complete); 42501 = insufficient_privilege.

begin;

create extension if not exists pgtap with schema extensions;
set local search_path = extensions, public;

-- plan: A 8 + B 11 + C 7 + D 11 + E 9 + F 6 + G 5 + H 7 + I 5 + J 6 + K 8 + L 3 + M 3 = 89.
-- Exact assertion-accounting is a standing convention (Epic-1 retro).
-- ⚠ Story 4.4 (+2): Section B +1 — the "grand_final row with a winner edge is REFUSED" assertion split into
-- two (a gf_order=1 row carrying the AD-21 reset edges is now ACCEPTED; a gf_order=2 terminal row with any
-- edge is still REFUSED — the widened arm did not weaken the CHECK). Section K +1 — the no-reset champion
-- path now also asserts tournament.final_match_id was set to the crowning row (DECISION A).
--
-- ⚠ SECTION L (+3) WAS ADDED AFTER MUTATION-TESTING THIS SUITE. Four defects were injected into the shipped
-- code to check the suite could see them: removing the loser drop (D2) -> 3 red; removing the bye cascade
-- (D3) -> red; writing before validating the whole cascade -> red. But DELETING ACCEPTANCE CRITERION 1 —
-- the `WHERE slot IS NULL OR = winner` predicate itself — left all 76 assertions GREEN, because
-- advance_match's pass-1 validation reaches the same verdict first and the predicate never decides
-- anything. A backstop nothing tests is a backstop that has already stopped working.
--
-- ⚠⚠ AND THE 4.3 CODE REVIEW THEN FOUND THE SAME DISEASE TWICE MORE — WHICH IS WHY THE PLAN GREW TO 87:
--   * SECTION M (+3). Section L tested the predicate but ALL THREE of its calls passed `p_walkover =>
--     false`, and `true` was the one mode in which the helper was actually unsafe: it wrote winner_entry
--     OUTSIDE the predicate, so it would silently RE-CROWN a decided match, or ERASE a winner on a NULL
--     entry, and return TRUE either way. Found by all three review layers; reproduced as service_role.
--   * SECTION D (+1). EVERY result-gate fixture had `winner_entry IS NULL`, and advance_match's two gates
--     return a BYTE-IDENTICAL payload — so DELETING THE WHOLE AC2 STATE GATE left all 79 assertions GREEN,
--     including the ⭐ "a `pending` match is REFUSED" one. The row that actually binds the gate is a
--     `pending` match WITH a winner; with the gate removed it advances, moving the bracket off unpublished
--     stats — exactly the AD-8 race. That row is now fixtured and asserted.
--
-- The lesson, three stories running (4.1, 4.2, 4.3): a suite is not evidence until a mutation makes it red.
-- Assert the VALUE, not the shape; assert the GUARD, not merely the path that happens to reach it.
select plan(89);

-- ════════════════════════════════════════════════════════════════════════════
-- Fixture (as postgres — bypasses RLS). Four tournaments, three real brackets.
-- ════════════════════════════════════════════════════════════════════════════
-- The three brackets are SEPARATE so one section's mutations cannot silently satisfy another's:
--   TADV  — the advance playground (E/F/G/H/I/K). Driven all the way into the Losers bracket.
--   TGATE — the AC2 result-gate refusals (D). Kept PRISTINE: a refusal must write nothing, and the only
--           way to prove that is to assert against a bracket nothing has legitimately touched.
--   TALT  — the `slot_taken` double-route (J). Its destination is deliberately poisoned.
--   TCHK  — no bracket at all: the raw-INSERT target for the CHECK tests (B).
insert into player (steamid64, display_name) values ('76561197960287930', 'AdminPlayer');
insert into app_role (steamid64, role) values ('76561197960287930', 'admin');
insert into player (steamid64, display_name)
select '765611979602878' || lpad(i::text, 2, '0'), 'Field ' || i
  from generate_series(1, 11) as i;

insert into season (name) values ('Season 1');
insert into tournament (season_id, name, state)
select (select id from season where name = 'Season 1'), v.n, 'registration_open'
  from (values ('TADV'), ('TGATE'), ('TALT'), ('TCHK')) as v(n);

-- 11 active players in each of the three bracket tournaments.
insert into roster_entry (tournament_id, steamid64, status)
select t.id, '765611979602878' || lpad(i::text, 2, '0'), 'active'
  from tournament t cross join generate_series(1, 11) as i
 where t.name in ('TADV', 'TGATE', 'TALT');

update tournament set state = 'registration_closed' where name in ('TADV', 'TGATE', 'TALT');

-- ── Helpers ─────────────────────────────────────────────────────────────────
create function pg_temp.tid(tname text) returns bigint language sql stable as $fn$
  select id from public.tournament where name = tname
$fn$;

-- "The entry that drew seed n" — deterministic by steamid64, matching the seed payload below.
create function pg_temp.re(tname text, n int) returns bigint language sql stable as $fn$
  select r.id
    from public.roster_entry r
    join public.tournament t on t.id = r.tournament_id
   where t.name = tname and r.status = 'active'
   order by r.steamid64
  offset (n - 1) limit 1
$fn$;

create function pg_temp.seeds(tname text, n int) returns jsonb language sql stable as $fn$
  select jsonb_agg(jsonb_build_object('roster_entry_id', pg_temp.re(tname, s), 'seed', s))
    from generate_series(1, n) as s
$fn$;

-- One routing edge, in the jsonb shape generate_bracket reads into match.winner_to_*/loser_to_*.
create function pg_temp.edge(b text, sl int, gf int, side text) returns jsonb language sql immutable as $fn$
  select jsonb_build_object('bracket', b, 'slot', sl, 'gf_order', gf, 'side', side)
$fn$;

-- ⚠ gf_order IS PART OF THE KEY, AND IT IS NOT OPTIONAL (4.3 code review). These helpers used to resolve on
-- (tournament, bracket, bracket_slot) alone. That is unique TODAY only because there is exactly one
-- grand_final row — but STORY 4.4 adds the AD-21 reset row at grand_final / slot 0 / gf_order = 2, at which
-- point `mid('TADV','grand_final',0)` returns TWO rows, raises 21000 ("more than one row returned by a
-- subquery used as an expression"), and ABORTS THIS ENTIRE FILE — not just the section that uses it. The
-- failure would be read as 4.4's bug rather than as a landmine this story planted. Key on the same
-- structural identity `match_slot_uniq` does (0010:112-113): coalesce(gf_order, 0). Default 0 keeps every
-- existing winners/losers call site unchanged.
create function pg_temp.mid(tname text, br text, slot int, gf int default 0) returns bigint language sql stable as $fn$
  select m.id
    from public.match m
    join public.tournament t on t.id = m.tournament_id
   where t.name = tname and m.bracket = br and m.bracket_slot = slot
     and coalesce(m.gf_order, 0) = coalesce(gf, 0)
$fn$;

-- The competitor seated on one side of one node — the thing almost every assertion below reads.
create function pg_temp.comp(tname text, br text, slot int, side text, gf int default 0) returns bigint language sql stable as $fn$
  select case when side = 'a' then m.competitor_a else m.competitor_b end
    from public.match m
    join public.tournament t on t.id = m.tournament_id
   where t.name = tname and m.bracket = br and m.bracket_slot = slot
     and coalesce(m.gf_order, 0) = coalesce(gf, 0)
$fn$;

-- How many nodes currently seat this entry. Two-loss elimination is proven by this NOT growing (F).
create function pg_temp.seats(tname text, entry bigint) returns int language sql stable as $fn$
  select count(*)::int
    from public.match m
    join public.tournament t on t.id = m.tournament_id
   where t.name = tname and (m.competitor_a = entry or m.competitor_b = entry)
$fn$;

create function pg_temp.audits(tname text) returns int language sql stable as $fn$
  select count(*)::int
    from public.audit_log a
    join public.tournament t on t.id = a.tournament_id
   where t.name = tname and a.action = 'advance'
$fn$;

create function pg_temp.msgs(tname text) returns int language sql stable as $fn$
  select count(*)::int
    from realtime.messages m
   where m.topic = 'tournament:' || pg_temp.tid(tname)::text
$fn$;

-- ⚠ realtime.messages is RANGE-partitioned on inserted_at, and its partitions are created by a Realtime
-- BACKGROUND JOB. `realtime.send` swallows its own errors by design (EXCEPTION WHEN OTHERS -> WARNING), so
-- if today's partition were missing the emit would fail SILENTLY and Section I would go red for a reason
-- that has nothing to do with this story. Make the suite's own precondition true rather than trust a
-- background job. (No-op in the normal case; rolled back with everything else.)
do $$
declare v_d date := current_date;
begin
  if not exists (
    select 1 from pg_class c
      join pg_inherits i on i.inhrelid = c.oid
     where i.inhparent = 'realtime.messages'::regclass
       and c.relname = 'messages_' || to_char(v_d, 'YYYY_MM_DD')
  ) then
    execute format(
      'create table realtime.messages_%s partition of realtime.messages for values from (%L) to (%L)',
      to_char(v_d, 'YYYY_MM_DD'), v_d::timestamp, (v_d + 1)::timestamp
    );
  end if;
end $$;

-- ── The REAL 11-player skeleton (a golden snapshot of generateBracket()'s output) ────────────────────
-- bracketSize 16 -> 30 rows. Seeds 1-5 draw byes (the top seeds, deterministically — AC3 of Story 4.1).
-- NINE `bye` rows + ONE `void` row. Read the losers block carefully, because it is where this story lives:
--   losers/0 = 'bye'  <- fed by W-R1 s0 (a bye: NO loser) and W-R1 s1 (a real match: ONE loser arrives)
--   losers/1 = 'void' <- fed by W-R1 s2 and s3, BOTH byes: NOBODY can ever arrive. Never played.
create function pg_temp.matches11(t text) returns jsonb language sql stable as $fn$
  select jsonb_agg(jsonb_build_object(
           'bracket', v.b, 'bracket_position', v.p, 'bracket_slot', v.sl, 'gf_order', v.gf,
           'competitor_a', v.ca, 'competitor_b', v.cb, 'winner_entry', v.we, 'state', v.st,
           'winner_to', v.wt, 'loser_to', v.lt))
    from (values
      ('winners', 'Winners R1', 0, null::int, pg_temp.re(t, 1), null::bigint, pg_temp.re(t, 1), 'bye', pg_temp.edge('winners', 8, null, 'a'), pg_temp.edge('losers', 0, null, 'a')),
      ('winners', 'Winners R1', 1, null::int, pg_temp.re(t, 8), pg_temp.re(t, 9), null::bigint, 'declared', pg_temp.edge('winners', 8, null, 'b'), pg_temp.edge('losers', 0, null, 'b')),
      ('winners', 'Winners R1', 2, null::int, pg_temp.re(t, 4), null::bigint, pg_temp.re(t, 4), 'bye', pg_temp.edge('winners', 9, null, 'a'), pg_temp.edge('losers', 1, null, 'a')),
      ('winners', 'Winners R1', 3, null::int, pg_temp.re(t, 5), null::bigint, pg_temp.re(t, 5), 'bye', pg_temp.edge('winners', 9, null, 'b'), pg_temp.edge('losers', 1, null, 'b')),
      ('winners', 'Winners R1', 4, null::int, pg_temp.re(t, 2), null::bigint, pg_temp.re(t, 2), 'bye', pg_temp.edge('winners', 10, null, 'a'), pg_temp.edge('losers', 2, null, 'a')),
      ('winners', 'Winners R1', 5, null::int, pg_temp.re(t, 7), pg_temp.re(t, 10), null::bigint, 'declared', pg_temp.edge('winners', 10, null, 'b'), pg_temp.edge('losers', 2, null, 'b')),
      ('winners', 'Winners R1', 6, null::int, pg_temp.re(t, 3), null::bigint, pg_temp.re(t, 3), 'bye', pg_temp.edge('winners', 11, null, 'a'), pg_temp.edge('losers', 3, null, 'a')),
      ('winners', 'Winners R1', 7, null::int, pg_temp.re(t, 6), pg_temp.re(t, 11), null::bigint, 'declared', pg_temp.edge('winners', 11, null, 'b'), pg_temp.edge('losers', 3, null, 'b')),
      ('winners', 'Winners R2', 8, null::int, pg_temp.re(t, 1), null::bigint, null::bigint, 'declared', pg_temp.edge('winners', 12, null, 'a'), pg_temp.edge('losers', 5, null, 'b')),
      ('winners', 'Winners R2', 9, null::int, pg_temp.re(t, 4), pg_temp.re(t, 5), null::bigint, 'declared', pg_temp.edge('winners', 12, null, 'b'), pg_temp.edge('losers', 4, null, 'b')),
      ('winners', 'Winners R2', 10, null::int, pg_temp.re(t, 2), null::bigint, null::bigint, 'declared', pg_temp.edge('winners', 13, null, 'a'), pg_temp.edge('losers', 7, null, 'b')),
      ('winners', 'Winners R2', 11, null::int, pg_temp.re(t, 3), null::bigint, null::bigint, 'declared', pg_temp.edge('winners', 13, null, 'b'), pg_temp.edge('losers', 6, null, 'b')),
      ('winners', 'Winners R3', 12, null::int, null::bigint, null::bigint, null::bigint, 'declared', pg_temp.edge('winners', 14, null, 'a'), pg_temp.edge('losers', 11, null, 'b')),
      ('winners', 'Winners R3', 13, null::int, null::bigint, null::bigint, null::bigint, 'declared', pg_temp.edge('winners', 14, null, 'b'), pg_temp.edge('losers', 10, null, 'b')),
      ('winners', 'Winners R4', 14, null::int, null::bigint, null::bigint, null::bigint, 'declared', pg_temp.edge('grand_final', 0, 1, 'a'), pg_temp.edge('losers', 13, null, 'b')),
      ('losers', 'Losers R1', 0, null::int, null::bigint, null::bigint, null::bigint, 'bye', pg_temp.edge('losers', 4, null, 'a'), null::jsonb),
      ('losers', 'Losers R1', 1, null::int, null::bigint, null::bigint, null::bigint, 'void', pg_temp.edge('losers', 5, null, 'a'), null::jsonb),
      ('losers', 'Losers R1', 2, null::int, null::bigint, null::bigint, null::bigint, 'bye', pg_temp.edge('losers', 6, null, 'a'), null::jsonb),
      ('losers', 'Losers R1', 3, null::int, null::bigint, null::bigint, null::bigint, 'bye', pg_temp.edge('losers', 7, null, 'a'), null::jsonb),
      ('losers', 'Losers R2', 4, null::int, null::bigint, null::bigint, null::bigint, 'declared', pg_temp.edge('losers', 8, null, 'a'), null::jsonb),
      ('losers', 'Losers R2', 5, null::int, null::bigint, null::bigint, null::bigint, 'bye', pg_temp.edge('losers', 8, null, 'b'), null::jsonb),
      ('losers', 'Losers R2', 6, null::int, null::bigint, null::bigint, null::bigint, 'declared', pg_temp.edge('losers', 9, null, 'a'), null::jsonb),
      ('losers', 'Losers R2', 7, null::int, null::bigint, null::bigint, null::bigint, 'declared', pg_temp.edge('losers', 9, null, 'b'), null::jsonb),
      ('losers', 'Losers R3', 8, null::int, null::bigint, null::bigint, null::bigint, 'declared', pg_temp.edge('losers', 10, null, 'a'), null::jsonb),
      ('losers', 'Losers R3', 9, null::int, null::bigint, null::bigint, null::bigint, 'declared', pg_temp.edge('losers', 11, null, 'a'), null::jsonb),
      ('losers', 'Losers R4', 10, null::int, null::bigint, null::bigint, null::bigint, 'declared', pg_temp.edge('losers', 12, null, 'a'), null::jsonb),
      ('losers', 'Losers R4', 11, null::int, null::bigint, null::bigint, null::bigint, 'declared', pg_temp.edge('losers', 12, null, 'b'), null::jsonb),
      ('losers', 'Losers R5', 12, null::int, null::bigint, null::bigint, null::bigint, 'declared', pg_temp.edge('losers', 13, null, 'a'), null::jsonb),
      ('losers', 'Losers R6', 13, null::int, null::bigint, null::bigint, null::bigint, 'declared', pg_temp.edge('grand_final', 0, 1, 'b'), null::jsonb),
      -- AD-21 (Story 4.4): gf_order=1 carries the CONDITIONAL reset edges (winner -> reset side b, loser ->
      -- reset side a); gf_order=2 is the terminal edgeless reset row (its winner is the champion).
      ('grand_final', 'Grand Final', 0, 1, null::bigint, null::bigint, null::bigint, 'declared', pg_temp.edge('grand_final', 0, 2, 'b'), pg_temp.edge('grand_final', 0, 2, 'a')),
      ('grand_final', 'Grand Final (reset)', 0, 2, null::bigint, null::bigint, null::bigint, 'declared', null::jsonb, null::jsonb)
    ) as v(b, p, sl, gf, ca, cb, we, st, wt, lt)
$fn$;

-- ── Generate all three brackets through the REAL RPC, then FREEZE their formats through the REAL 4.2 RPC ──
-- The format declare is not decoration: `match_live_requires_locked_format` (0012) refuses state='resolved'
-- on an unlocked match, so a result cannot even be FIXTURED without it. It is also exactly the cross-story
-- regression Section K pins — the advance must work on a format-LOCKED match.
create temp table rpc_log (tag text primary key, r jsonb);
grant select, insert on rpc_log to service_role;

insert into rpc_log
select v.tag,
       public.generate_bracket(pg_temp.tid(v.tag), '76561197960287930',
                               '{"algorithm":"fisher-yates"}'::jsonb,
                               pg_temp.seeds(v.tag, 11), pg_temp.matches11(v.tag))
  from (values ('TADV'), ('TGATE'), ('TALT')) as v(tag);

-- Bulk declare: locks exactly the 20 `declared` rows and leaves all 10 bye/void rows alone (AD-9).
insert into rpc_log
select 'fmt_' || v.tag,
       public.declare_match_format(pg_temp.tid(v.tag), null, 'mr12', 'ot_mr3', '76561197960287930', false)
  from (values ('TADV'), ('TGATE'), ('TALT')) as v(tag);

-- ════════════════════════════════════════════════════════════════════════════
-- Section A — the objects exist + the EXECUTE grant matrix (7)
-- ════════════════════════════════════════════════════════════════════════════
-- ⚠ There is NO advance ROUTE, and that is AC2, not an omission: the advance is a CONSEQUENCE of a result
-- transition, "never an independent button that races publish" (AD-8). Stories 4.5/4.6 call this function
-- from INSIDE their own transactions. The grant IS the boundary.
select has_function('public'::name, 'advance_match'::name, ARRAY['bigint','text','boolean']::name[],
  'advance_match(bigint, text, boolean) exists — the mechanism 4.5/4.6 call inside their own transactions');
select has_function('public'::name, 'match_place_competitor'::name, ARRAY['bigint','text','bigint','boolean']::name[],
  'match_place_competitor(...) exists — the ONE place AC1''s conditional predicate is written');

select is(has_function_privilege('service_role', 'public.advance_match(bigint,text,boolean)', 'execute'), true,
  'service_role CAN execute advance_match (the single writer — AD-2)');
select is(has_function_privilege('anon', 'public.advance_match(bigint,text,boolean)', 'execute'), false,
  'anon CANNOT execute advance_match — the revoke-from-PUBLIC is LOAD-BEARING (CREATE FUNCTION grants EXECUTE to PUBLIC by default, and anon inherits it)');
select is(has_function_privilege('authenticated', 'public.advance_match(bigint,text,boolean)', 'execute'), false,
  'authenticated CANNOT execute advance_match — a logged-in viewer cannot advance the bracket off the Data API');
select is(has_function_privilege('service_role', 'public.match_place_competitor(bigint,text,bigint,boolean)', 'execute'), true,
  'service_role CAN execute match_place_competitor');
select is(has_function_privilege('anon', 'public.match_place_competitor(bigint,text,bigint,boolean)', 'execute'), false,
  'anon CANNOT execute match_place_competitor — the helper is internal, not an API');
-- ⚠ The `authenticated` half was MISSING (4.3 code review). Task 7 demands the full matrix, and this is the
-- function whose grant matters MOST: it is the one 4.5/4.6 are told to call directly, and the one that
-- writes winner_entry. A logged-in viewer must not be able to seat themselves into the bracket.
select is(has_function_privilege('authenticated', 'public.match_place_competitor(bigint,text,bigint,boolean)', 'execute'), false,
  'authenticated CANNOT execute match_place_competitor — a logged-in viewer cannot seat a competitor, nor crown one, off the Data API');

-- ════════════════════════════════════════════════════════════════════════════
-- Section B — D1: match_routing_complete makes a BRICK unrepresentable (11)
-- ════════════════════════════════════════════════════════════════════════════
-- A bracket row with no way out is a BRICK: nothing can ever advance out of it, and `match` has NO DELETE
-- grant — so it is unrecoverable. This is the constraint that makes shipping one impossible.
select is(
  (select count(*)::int from information_schema.columns
    where table_schema = 'public' and table_name = 'match'
      and column_name in ('winner_to_bracket','winner_to_slot','winner_to_gf_order','winner_to_side',
                          'loser_to_bracket','loser_to_slot','loser_to_gf_order','loser_to_side')),
  8, 'D1: all EIGHT routing columns exist on match (the bracket DAG, as STRUCTURE — not match_ids)');

-- ⚠⚠ EVERY throws_ok BELOW NAMES ITS CONSTRAINT, AND THAT IS NOT PEDANTRY (4.3 code review).
-- `match` now carries TEN CHECK constraints and EVERY ONE of them raises 23514. A `throws_ok(..., '23514',
-- null, ...)` therefore asserts only "some CHECK fired" — it cannot tell match_routing_complete from
-- match_winner_edge_shape from match_gf_order_guard, which is the ENTIRE distinction this section is named
-- for. This file's own comments warn about exactly that hazard in the 0010/0011/0012 fixtures ("a routing
-- violation is 23514 — the SAME SQLSTATE those throws_ok's assert, so an edge-less fixture would let them
-- pass FOR THE WRONG REASON") and then reproduced it here. Pin the constraint by name: each of the seven
-- below trips exactly one, deterministically, and now says which.
select throws_ok(
  $$ insert into match (tournament_id, bracket, bracket_position, bracket_slot)
       values (pg_temp.tid('TCHK'), 'winners', 'Winners R1', 1) $$,
  '23514', 'new row for relation "match" violates check constraint "match_routing_complete"',
  'D1: a `winners` row with NO edges is REFUSED by match_routing_complete — a row nothing can advance out of is a brick, and there is no DELETE grant to undo it');

-- ⭐ THE D2 BRICK, AND IT IS THE ONE THAT WOULD SHIP SILENTLY. A winners row with a winner edge and no
-- LOSER edge passes every "does the winner advance?" test ever written — and the Losers bracket never
-- receives anybody, so NO TOURNAMENT CAN EVER COMPLETE.
select throws_ok(
  $$ insert into match (tournament_id, bracket, bracket_position, bracket_slot,
                        winner_to_bracket, winner_to_slot, winner_to_side)
       values (pg_temp.tid('TCHK'), 'winners', 'Winners R1', 2, 'winners', 9, 'a') $$,
  '23514', 'new row for relation "match" violates check constraint "match_routing_complete"',
  'D1/D2: a `winners` row with a winner edge but NO LOSER-DROP edge is REFUSED by match_routing_complete — without the drop the Losers bracket never fills and no event can finish');

select throws_ok(
  $$ insert into match (tournament_id, bracket, bracket_position, bracket_slot,
                        winner_to_bracket, winner_to_slot, winner_to_side,
                        loser_to_bracket, loser_to_slot, loser_to_side)
       values (pg_temp.tid('TCHK'), 'losers', 'Losers R1', 3, 'losers', 9, 'a', 'losers', 10, 'a') $$,
  '23514', 'new row for relation "match" violates check constraint "match_routing_complete"',
  'D1/FR-6: a `losers` row carrying a LOSER edge is REFUSED by match_routing_complete — a Losers loser has taken their SECOND loss, and the ABSENCE of the edge IS two-loss elimination');

-- ⭐ AD-21 (Story 4.4) — THE WIDENED ARM, PROVEN IN BOTH DIRECTIONS. gf_order=1 MAY carry the two reset
-- edges (winner/loser -> the reset row, grand_final gf_order=2); gf_order=2 stays TERMINAL. The widening
-- did NOT weaken the CHECK — a GF-1 edge aimed anywhere but the reset, and ANY edge on the terminal reset
-- row, are both still unrepresentable.
select lives_ok(
  $$ insert into match (tournament_id, bracket, bracket_position, bracket_slot, gf_order,
                        winner_to_bracket, winner_to_slot, winner_to_gf_order, winner_to_side,
                        loser_to_bracket,  loser_to_slot,  loser_to_gf_order,  loser_to_side)
       values (pg_temp.tid('TCHK'), 'grand_final', 'Grand Final', 0, 1,
               'grand_final', 0, 2, 'b', 'grand_final', 0, 2, 'a') $$,
  'D1/AD-21: a `grand_final` gf_order=1 row carrying the two reset edges (-> grand_final gf_order=2) is ACCEPTED — the widened arm makes the AD-21 conditional representable');
select throws_ok(
  $$ insert into match (tournament_id, bracket, bracket_position, bracket_slot, gf_order,
                        winner_to_bracket, winner_to_slot, winner_to_side)
       values (pg_temp.tid('TCHK'), 'grand_final', 'Grand Final (reset)', 0, 2, 'winners', 9, 'a') $$,
  '23514', 'new row for relation "match" violates check constraint "match_routing_complete"',
  'D1/AD-21: the TERMINAL reset row (gf_order=2) carrying ANY edge is REFUSED by match_routing_complete — its winner is the CHAMPION and advances nowhere');

select throws_ok(
  $$ insert into match (tournament_id, bracket, bracket_position, bracket_slot,
                        winner_to_bracket, winner_to_slot,
                        loser_to_bracket, loser_to_slot, loser_to_side)
       values (pg_temp.tid('TCHK'), 'winners', 'Winners R1', 4, 'winners', 9, 'losers', 10, 'a') $$,
  '23514', 'new row for relation "match" violates check constraint "match_winner_edge_shape"',
  'D1: HALF an edge (a bracket + slot with no SIDE) is REFUSED by match_winner_edge_shape — an edge is all-or-nothing, or it resolves to nothing (or to the wrong seat)');

select throws_ok(
  $$ insert into match (tournament_id, bracket, bracket_position, bracket_slot,
                        winner_to_bracket, winner_to_slot, winner_to_side,
                        loser_to_bracket, loser_to_slot, loser_to_side)
       values (pg_temp.tid('TCHK'), 'winners', 'Winners R1', 5, 'grand_final', 0, 'a', 'losers', 10, 'a') $$,
  '23514', 'new row for relation "match" violates check constraint "match_winner_edge_gf_order"',
  'D1: an edge to grand_final with a NULL gf_order is REFUSED by match_winner_edge_gf_order — it would resolve through coalesce(gf_order,0)=0 and match NOTHING, dead-ending the bracket at the final');

-- ⚠ THE VALUE, NOT JUST THE NULL-NESS (4.3 code review). The constraint originally asserted only
-- `gf_order is not null`, so an edge naming gf_order = 7 was representable, resolved to NO row, and raised
-- at advance time on an already-live bracket — the exact outcome the constraint exists to prevent.
select throws_ok(
  $$ insert into match (tournament_id, bracket, bracket_position, bracket_slot,
                        winner_to_bracket, winner_to_slot, winner_to_gf_order, winner_to_side,
                        loser_to_bracket, loser_to_slot, loser_to_side)
       values (pg_temp.tid('TCHK'), 'winners', 'Winners R1', 7, 'grand_final', 0, 7, 'a', 'losers', 10, 'a') $$,
  '23514', 'new row for relation "match" violates check constraint "match_winner_edge_gf_order"',
  'D1 ⭐ an edge to grand_final with gf_order = 7 is REFUSED — the guard mirrors match_gf_order_guard''s VALUES (1,2), not merely its NOT NULL; a legal-looking gf_order that names no row dead-ends the bracket just as surely as a NULL one');

select throws_ok(
  $$ insert into match (tournament_id, bracket, bracket_position, bracket_slot,
                        winner_to_bracket, winner_to_slot, winner_to_side,
                        loser_to_bracket, loser_to_slot, loser_to_side)
       values (pg_temp.tid('TCHK'), 'winners', 'Winners R1', 6, 'winners', 9, 'c', 'losers', 10, 'a') $$,
  '23514', 'new row for relation "match" violates check constraint "match_winner_to_side_check"',
  'D1: winner_to_side = ''c'' is REFUSED by match_winner_to_side_check — a match has exactly two seats (the closed-set-text convention)');

-- The positive control: with BOTH edges, the same row lives. Without this the section above would still
-- pass if the CHECK simply rejected everything.
select lives_ok(
  $$ insert into match (tournament_id, bracket, bracket_position, bracket_slot,
                        winner_to_bracket, winner_to_slot, winner_to_side,
                        loser_to_bracket, loser_to_slot, loser_to_side)
       values (pg_temp.tid('TCHK'), 'winners', 'Winners R1', 7, 'winners', 9, 'a', 'losers', 10, 'b') $$,
  'D1: a `winners` row declaring BOTH exits is accepted (the positive control — the CHECK is a filter, not a wall)');

-- ════════════════════════════════════════════════════════════════════════════
-- Section C — D1: the REAL generate_bracket PERSISTS the edges (7)
-- ════════════════════════════════════════════════════════════════════════════
select is((select (r->>'ok')::boolean from rpc_log where tag = 'TADV'), true,
  'D1: generate_bracket accepted the edge-bearing payload (create-or-replace kept its signature AND its grants)');
select is((select (r->>'match_count')::int from rpc_log where tag = 'TADV'), 31,
  'D1: an 11-player field commits 31 match rows (2*16-1, incl. the AD-21 reset row) — the complete skeleton');

select is(
  (select count(*)::int from match where tournament_id = pg_temp.tid('TADV') and bracket = 'winners'
     and winner_to_bracket is not null and loser_to_bracket is not null),
  15, 'D1: all 15 `winners` rows carry BOTH edges — every one of them drops a loser into the LB');
select is(
  (select count(*)::int from match where tournament_id = pg_temp.tid('TADV') and bracket = 'losers'
     and winner_to_bracket is not null),
  14, 'D1: all 14 `losers` rows carry a winner edge');
select is(
  (select count(*)::int from match where tournament_id = pg_temp.tid('TADV') and bracket = 'losers'
     and loser_to_bracket is not null),
  0, 'D1/FR-6: NO `losers` row carries a loser edge — two-loss elimination, derived from the edges and proven by an ABSENCE');

select ok(
  (select winner_to_bracket is null and loser_to_bracket is null
     from match where tournament_id = pg_temp.tid('TADV') and bracket = 'grand_final' and gf_order = 2),
  'D1/AD-21: the RESET grand-final row (gf_order=2) carries NEITHER edge — the champion goes nowhere, the runner-up goes nowhere');

-- The two finals converge, and on the RIGHT sides. A swap here would seat both finalists on one seat.
select is(
  (select winner_to_bracket || '/' || winner_to_gf_order || '/' || winner_to_side
     from match where tournament_id = pg_temp.tid('TADV') and bracket = 'winners' and bracket_slot = 14)
  || ' + ' ||
  (select winner_to_bracket || '/' || winner_to_gf_order || '/' || winner_to_side
     from match where tournament_id = pg_temp.tid('TADV') and bracket = 'losers' and bracket_slot = 13),
  'grand_final/1/a + grand_final/1/b',
  'D1: the Winners Final routes to GF side A and the Losers Final to GF side B (the two finalists take different seats)');

-- ════════════════════════════════════════════════════════════════════════════
-- Section D — AC2: no RESULT, no advance. And a refusal writes NOTHING. (10)
-- ════════════════════════════════════════════════════════════════════════════
-- ⭐ THIS IS WHAT MAKES "CONSEQUENCE, NOT CONTROL" A MECHANISM RATHER THAN A COMMENT. Run on TGATE, which
-- NOTHING legitimate has touched — so "nothing was written" is a claim this section can actually prove.
set local role service_role;

-- Fixture the four non-terminal / non-result states on rows nothing routes into during this section.
update match set state = 'live'     where id = pg_temp.mid('TGATE', 'winners', 12);
update match set state = 'pending'  where id = pg_temp.mid('TGATE', 'winners', 13);
update match set state = 'resolved' where id = pg_temp.mid('TGATE', 'losers', 12);   -- winner_entry stays NULL
update match set state = 'rolled_back' where id = pg_temp.mid('TGATE', 'losers', 13);

select is(public.advance_match(pg_temp.mid('TGATE', 'winners', 5), '76561197960287930') ->> 'reason', 'not_resolved',
  'AC2: a `declared` match has produced no result — advancing it is REFUSED');
select is(public.advance_match(pg_temp.mid('TGATE', 'winners', 12), '76561197960287930') ->> 'reason', 'not_resolved',
  'AC2: a `live` match has produced no result — advancing it is REFUSED');

-- ⭐⭐ THE AD-8 CASE, PINNED BY NAME. Advancing a PENDING match is PRECISELY the "advance racing the
-- publish" that AD-8 exists to prevent (FR-13: Pending stats are excluded from bracket advancement).
select is(public.advance_match(pg_temp.mid('TGATE', 'winners', 13), '76561197960287930') ->> 'reason', 'not_resolved',
  'AC2 ⭐ a `pending` match is REFUSED — this is the "advance races the publish" failure AD-8 names, and the reason there is no independent advance control');

select is(public.advance_match(pg_temp.mid('TGATE', 'losers', 12), '76561197960287930') ->> 'reason', 'not_resolved',
  'AC2: a `resolved` match with a NULL winner_entry is REFUSED — a result without a winner is not a result');
select is(public.advance_match(pg_temp.mid('TGATE', 'losers', 1), '76561197960287930') ->> 'reason', 'not_resolved',
  'AC2: a `void` node is REFUSED — nothing can ever arrive at it, so nothing can ever leave');
select is(public.advance_match(pg_temp.mid('TGATE', 'losers', 13), '76561197960287930') ->> 'reason', 'not_resolved',
  'AC2: a `rolled_back` match advances nobody — un-advancing is Story 4.7''s job, not a re-advance');
select is(public.advance_match(999999999::bigint, '76561197960287930') ->> 'reason', 'bad_match',
  'AC2: a non-existent match id is REFUSED `bad_match` (the function takes an id and re-reads the DB — it never trusts a caller-supplied destination)');

-- ⭐⭐⭐ THE ASSERTION THE STATE GATE ACTUALLY NEEDED, AND THE ONE THIS SUITE DID NOT HAVE (4.3 code review).
-- EVERY fixture above has `winner_entry IS NULL`. advance_match has TWO sequential gates that return a
-- BYTE-IDENTICAL payload — `state not in (bye,forfeit,resolved,manual_resolved)` and `winner_entry is null`
-- — so the SECOND one satisfied every assertion in this section ON ITS OWN. Verified by mutation at review:
-- DELETING THE ENTIRE AC2 STATE GATE LEFT ALL 79 ASSERTIONS GREEN, including the ⭐ "pending is REFUSED" one
-- above. A `pending` row with no winner cannot advance anybody whether the gate exists or not, so it tests
-- nothing.
--
-- The row that actually binds the gate is a match with a KNOWN WINNER whose stats are still PENDING — which
-- is PRECISELY the "advance racing the publish" AD-8 exists to prevent. With the state gate removed, that
-- row advances: `{"ok":true,"advanced":2}`, the winner seated forward and the loser dropped, off a match
-- whose stats were never published. THIS assertion is what turns that mutation red.
--
-- (winners/1 is a real R1 match — two competitors, format locked by the bulk declare above.)
update match
   set state = 'pending', winner_entry = competitor_a
 where id = pg_temp.mid('TGATE', 'winners', 1);

select is(public.advance_match(pg_temp.mid('TGATE', 'winners', 1), '76561197960287930') ->> 'reason', 'not_resolved',
  'AC2 ⭐⭐ a `pending` match WITH A WINNER is REFUSED — its stats are not published, so its result is not final. THIS is the AD-8 race, and it is the ONLY assertion here that actually binds the state gate');

-- …and NONE of the eight wrote anything. Every guard runs BEFORE any write.
select is(pg_temp.audits('TGATE'), 0,
  'AC2: eight refusals wrote ZERO `advance` audit rows — a typed refusal RETURNS, so it must commit nothing');
-- ⚠ BOTH SEATS. The message says "ZERO competitors" but the query used to read `competitor_a` ONLY — and in
-- this very fixture the drop from winners/1 targets losers/0 SIDE B, so a leaked write from a broken guard
-- would land in exactly the column the assertion did not read, and stay green (4.3 code review).
select is(
  (select count(*)::int from match
    where tournament_id = pg_temp.tid('TGATE') and bracket = 'losers'
      and (competitor_a is not null or competitor_b is not null)),
  0, 'AC2: eight refusals seated ZERO competitors — on EITHER seat — and the Losers bracket of TGATE is still exactly as generated');
select is(pg_temp.msgs('TGATE'), 0,
  'AC3/AC2: a REFUSED advance emits NO Broadcast — the nudge announces a change, and nothing changed');

-- ════════════════════════════════════════════════════════════════════════════
-- Section E — AC1: the conditional write, and the REPLAY that is a no-op (9)
-- ════════════════════════════════════════════════════════════════════════════
-- TADV, Winners R1 slot 1: seeds 8 v 9, the first REAL match of the bracket.
--   winner -> winners/8 side b  (whose side a already holds seed 1, pre-advanced through a bye at generation)
--   loser  -> losers/0  side b  (a `bye` node -> the D3 cascade, Section G)
update match set state = 'resolved', winner_entry = pg_temp.re('TADV', 8)
 where id = pg_temp.mid('TADV', 'winners', 1);

insert into rpc_log values
  ('adv1', public.advance_match(pg_temp.mid('TADV', 'winners', 1), '76561197960287930'));

select is((select (r->>'ok')::boolean from rpc_log where tag = 'adv1'), true,
  'AC1: advancing a RESOLVED match succeeds');
select is((select (r->>'advanced')::int from rpc_log where tag = 'adv1'), 3,
  'AC1: THREE placements — the winner, the loser''s drop, AND the loser''s walkover cascade (D2 + D3 in one consequence)');
select is(pg_temp.comp('TADV', 'winners', 8, 'b'), pg_temp.re('TADV', 8),
  'AC1: the winner is seated in the EXACT seat winner_to names (winners/8, side b)');
select is(pg_temp.comp('TADV', 'winners', 8, 'a'), pg_temp.re('TADV', 1),
  'AC1: the OTHER seat of that node is untouched — the bye winner generation pre-advanced is still there (the write is conditional on ITS OWN side)');

-- ⭐ THE REPLAY. AC1's whole point: re-issuing the same advance is a NO-OP that still reports SUCCESS.
-- Snapshot the bracket's seat count FIRST — comparing the after-count to itself would be a tautology that
-- passes no matter what the replay did (the exact "the suite proved less than it claimed" trap the 4.1 and
-- 4.2 reviews each found once already).
insert into rpc_log
select 'seats_before_replay',
       jsonb_build_object('n', (select count(*)::int from match
                                 where tournament_id = pg_temp.tid('TADV')
                                   and (competitor_a is not null or competitor_b is not null)));

insert into rpc_log values
  ('adv1_replay', public.advance_match(pg_temp.mid('TADV', 'winners', 1), '76561197960287930'));

select is((select (r->>'ok')::boolean from rpc_log where tag = 'adv1_replay'), true,
  'AC1 ⭐ a REPLAY is SUCCESS, not a refusal — `WHERE slot IS NULL OR = winner` matches the row it already wrote, so a double-tap is idempotent by construction');
select is((select (r->>'advanced')::int from rpc_log where tag = 'adv1_replay'), 3,
  'AC1: the replay returns the IDENTICAL result (same input -> same output) — idempotency, not a special "already done" branch');
select is(pg_temp.comp('TADV', 'winners', 8, 'b'), pg_temp.re('TADV', 8),
  'AC1: the destination seat is UNCHANGED after the replay — no double-route');
select is(
  (select count(*)::int from match where tournament_id = pg_temp.tid('TADV')
     and (competitor_a is not null or competitor_b is not null)),
  (select (r ->> 'n')::int from rpc_log where tag = 'seats_before_replay'),
  'AC1: the replay seated nobody new ANYWHERE in the bracket (compared against a snapshot taken BEFORE it — not against itself)');
select is(pg_temp.audits('TADV'), 2,
  'D4: the replay DID write a second `advance` audit row — the audit is a log of admin ACTIONS, not of state deltas, and a silent double-tap is exactly what AD-8 wants visible');

-- ════════════════════════════════════════════════════════════════════════════
-- Section F — D3: THE BYE CASCADE. The reason this story exists. (6)
-- ════════════════════════════════════════════════════════════════════════════
-- ⚠ ORDERED BEFORE the D2 section ON PURPOSE. Section G below MUTATES the bracket further (it plays a
-- Losers match), and its fixture UPDATE would abort on match_winner_is_competitor if the cascade had not
-- run. That abort would take the whole file down BEFORE these assertions could name the actual defect —
-- so a broken cascade would go red for a confusing reason. Asserting the cascade FIRST means a regression
-- here reports itself. (Verified by mutation: removing the cascade turns exactly these red.)
--
-- The loser of winners/1 dropped into losers/0 — a `bye` node, because its OTHER feeder (winners/0) was a
-- bye and a bye has NO loser. Only ONE competitor can ever arrive there. If the advance left them sitting
-- in it waiting for an opponent who cannot exist, the Losers bracket would STALL AT THE FIRST WALKOVER.
select is((select state from match where id = pg_temp.mid('TADV', 'losers', 0)), 'bye',
  'D3: the drop target IS a walkover node — one feeder was a bye, so only one competitor can ever reach it');
select is((select winner_entry from match where id = pg_temp.mid('TADV', 'losers', 0)), pg_temp.re('TADV', 9),
  'D3 ⭐ the arrival WON IT UNPLAYED — the advance set winner_entry in the same UPDATE that seated them (match_winner_is_competitor forbids doing it in two statements)');
select is(pg_temp.comp('TADV', 'losers', 4, 'a'), pg_temp.re('TADV', 9),
  'D3 ⭐⭐ …AND THEY DID NOT STOP THERE. The advance CONTINUED from the walkover and has already seated them in the next node. THIS is the assertion that proves the Losers bracket does not stall');

select is(
  (select jsonb_array_length(r -> 'hops') from rpc_log where tag = 'adv1'), 3,
  'D3: the hops array records all three placements of the single consequence');
select ok(
  (select bool_or((h ->> 'walkover')::boolean)
     from rpc_log, jsonb_array_elements(r -> 'hops') as h where tag = 'adv1'),
  'D3: one of those hops is flagged `walkover` — the cascade is legible in the audit trail, not hidden');

-- The void node: NOTHING may ever arrive there. Both of ITS feeders (winners/2, winners/3) were byes.
select ok(
  (select competitor_a is null and competitor_b is null and winner_entry is null
     from match where id = pg_temp.mid('TADV', 'losers', 1)),
  'D3: the `void` node is STILL untouched — no competitor, no winner. It is never played and advances nobody (advance_match RAISES if routing ever sends someone there)');

-- ════════════════════════════════════════════════════════════════════════════
-- Section G — D2: the loser drops, and a LOSERS loser is ELIMINATED (4)
-- ════════════════════════════════════════════════════════════════════════════
select is(pg_temp.comp('TADV', 'losers', 0, 'b'), pg_temp.re('TADV', 9),
  'D2: THE LOSER DROPPED. AC1 says only "winner" — but without this the Losers bracket never receives ANYBODY and no tournament can ever complete');

-- Now play a LOSERS match and prove its loser goes NOWHERE. First fill losers/4's other seat by resolving
-- winners/9 (seeds 4 v 5, two bye winners): its loser drops to losers/4 side b.
update match set state = 'resolved', winner_entry = pg_temp.re('TADV', 4)
 where id = pg_temp.mid('TADV', 'winners', 9);
select ok((public.advance_match(pg_temp.mid('TADV', 'winners', 9), '76561197960287930') ->> 'ok')::boolean,
  'D2: a second Winners result advances (its loser drops into losers/4, filling the seat opposite the walkover survivor)');

-- losers/4 now holds {a: seed 9 (via the bye cascade), b: seed 5 (the fresh dropdown)}. Play it.
update match set state = 'resolved', winner_entry = pg_temp.re('TADV', 9)
 where id = pg_temp.mid('TADV', 'losers', 4);

insert into rpc_log values
  ('adv_lb', public.advance_match(pg_temp.mid('TADV', 'losers', 4), '76561197960287930'));

select is((select (r->>'advanced')::int from rpc_log where tag = 'adv_lb'), 1,
  'D2 ⭐ a LOSERS match advances EXACTLY ONE player — the winner. Its loser has taken their SECOND loss and is ELIMINATED');

-- ⚠ `advanced` COUNTS PASS-1 PLANS, NOT WRITES — AND IT NEVER SAYS *WHERE* (4.3 code review). A regression
-- that routed this winner into the WRONG SEAT would still report `advanced = 1`, and the elimination
-- assertion below would be unaffected — so this section would stay green on a mis-routed bracket. Follow
-- the edge and read the seat: assert the winner ARRIVED, not merely that a placement was counted for them.
select is(
  (select case when m.winner_to_side = 'a' then d.competitor_a else d.competitor_b end
     from match m
     join match d
       on  d.tournament_id         = m.tournament_id
      and  d.bracket               = m.winner_to_bracket
      and  d.bracket_slot          = m.winner_to_slot
      and  coalesce(d.gf_order, 0) = coalesce(m.winner_to_gf_order, 0)
    where m.id = pg_temp.mid('TADV', 'losers', 4)),
  pg_temp.re('TADV', 9),
  'D2 ⭐ …and the winner ACTUALLY ARRIVED in the exact seat losers/4''s winner_to edge names — not merely that one placement was counted');

select is(pg_temp.seats('TADV', pg_temp.re('TADV', 5)), 3,
  'D2/FR-6: the eliminated player gained NO new seat anywhere (still only the 3 nodes they already played). Elimination is proven by an ABSENCE — the losers row has no loser edge to follow');

-- ════════════════════════════════════════════════════════════════════════════
-- Section H — D4: the audit row's COLUMN VALUES. Assert EVERY key. (7)
-- ════════════════════════════════════════════════════════════════════════════
-- 4.2's review found that asserting ONE key of a jsonb_build_object lets a typo in any of the others NULL
-- the payload with the suite fully green. So: every key, or it is not proven.
set local role postgres;

select is(
  (select count(*)::int from audit_log
    where tournament_id = pg_temp.tid('TADV') and action = 'advance'
      and target_match_id = pg_temp.mid('TADV', 'winners', 1)),
  2, 'D4: ONE `advance` audit row per CALL (two calls on winners/1: the advance and its replay) — not one per hop; a bye cascade is a single admin consequence');
select is(
  (select count(*)::int from audit_log a
    where a.tournament_id = pg_temp.tid('TADV') and a.action = 'advance' and a.target_match_id is null),
  0, 'D4: every advance row populates target_match_id — it names the SOURCE match (the result), not a destination');
select is(
  (select detail ->> 'winner_entry' from audit_log
    where target_match_id = pg_temp.mid('TADV', 'winners', 1) and action = 'advance' order by id limit 1),
  pg_temp.re('TADV', 8)::text, 'D4: detail.winner_entry is the match''s winner');
select is(
  (select detail ->> 'loser_entry' from audit_log
    where target_match_id = pg_temp.mid('TADV', 'winners', 1) and action = 'advance' order by id limit 1),
  pg_temp.re('TADV', 9)::text, 'D4: detail.loser_entry is the competitor who is NOT the winner (NULL for a bye — one expression handles Bye/Forfeit/Resolved)');
select is(
  (select jsonb_array_length(detail -> 'hops') from audit_log
    where target_match_id = pg_temp.mid('TADV', 'winners', 1) and action = 'advance' order by id limit 1),
  3, 'D4: detail.hops carries all three placements');
select is(
  (select h ->> 'side' from audit_log a, jsonb_array_elements(a.detail -> 'hops') with ordinality as t(h, n)
    where a.target_match_id = pg_temp.mid('TADV', 'winners', 1) and a.action = 'advance' and t.n = 1
    order by a.id limit 1),
  'b', 'D4: each hop records its SIDE (the winner took winners/8 side b) — the audit says WHERE, not merely THAT');
select is(
  (select detail ->> 'champion' from audit_log
    where target_match_id = pg_temp.mid('TADV', 'winners', 1) and action = 'advance' order by id limit 1),
  null::text, 'D4: detail.champion is NULL for a non-final advance (it is only set when the Grand Final''s winner falls out — Section K)');

-- ════════════════════════════════════════════════════════════════════════════
-- Section I — AC3: the Broadcast, post-commit BY CONSTRUCTION (5)
-- ════════════════════════════════════════════════════════════════════════════
-- `realtime.send` INSERTS into realtime.messages inside THIS transaction, and Realtime ships it off the
-- replication slot. So nothing is delivered unless the transaction COMMITS — and this whole suite runs in
-- `begin … rollback`, which is itself the proof that a rolled-back advance delivers nothing.
select cmp_ok(pg_temp.msgs('TADV'), '>', 0,
  'AC3: a committed advance emitted a Broadcast row into realtime.messages (written IN the advance''s own transaction — the emit cannot outrun its own commit)');
select is(
  (select count(*)::int from realtime.messages
    where topic = 'tournament:' || pg_temp.tid('TADV')::text and event = 'bracket.advanced'),
  (select count(*)::int from realtime.messages where topic = 'tournament:' || pg_temp.tid('TADV')::text),
  'AC3: every message on the channel is the `bracket.advanced` event — named by the SEMANTIC CHANGE (AD-11 / SPINE:230), not by the table it touched');
select is(
  (select bool_and(private = false) from realtime.messages
    where topic = 'tournament:' || pg_temp.tid('TADV')::text),
  true, 'AC3: the topic is the PUBLIC channel `tournament:<id>` (AD-11) — private => false');
select is(
  (select count(*)::int from realtime.messages
    where topic = 'tournament:' || pg_temp.tid('TADV')::text
      and (payload ->> 'match_id')::bigint = pg_temp.mid('TADV', 'winners', 1)
      and (payload ->> 'winner_entry')::bigint = pg_temp.re('TADV', 8)),
  2, 'AC3: the payload carries the semantic change (which match, which winner) — the nudge says WHAT happened; the viewer re-reads published truth (Broadcast is never the source of truth)');
select is(pg_temp.msgs('TGATE'), 0,
  'AC3: the pristine bracket (TGATE, seven refusals) emitted NOTHING — an emit is a consequence of a WRITE, not of a call');

-- ════════════════════════════════════════════════════════════════════════════
-- Section J — AC1: the DOUBLE-ROUTE IS REFUSED, and the refusal commits NOTHING (6)
-- ════════════════════════════════════════════════════════════════════════════
-- The assertion the whole AC exists for. "Re-routing a different winner requires an explicit rollback
-- first" (AD-8 / SOLUTION-DESIGN §7) — so `slot_taken` is a REFUSAL, never an overwrite. Rollback is 4.7.
--
-- ⭐⭐ AND THE HARD HALF, WHICH IS WHY advance_match VALIDATES THE WHOLE CASCADE BEFORE WRITING ANY OF IT:
-- here the poisoned seat is the LOSER's destination, while the WINNER's own seat is free. A one-pass
-- implementation would place the winner, THEN discover the loser's seat was taken, and return
-- `{ok:false}` — with a half-applied advance committed underneath it, because a RETURNED refusal does not
-- roll anything back. The winner must NOT have moved.
set local role service_role;

-- Poison losers/0 side b (the loser's drop target) with a player who has no business being there.
update match set competitor_b = pg_temp.re('TALT', 11) where id = pg_temp.mid('TALT', 'losers', 0);
update match set state = 'resolved', winner_entry = pg_temp.re('TALT', 8)
 where id = pg_temp.mid('TALT', 'winners', 1);

insert into rpc_log values
  ('alt', public.advance_match(pg_temp.mid('TALT', 'winners', 1), '76561197960287930'));

select is((select r ->> 'reason' from rpc_log where tag = 'alt'), 'slot_taken',
  'AC1: a destination seat held by a DIFFERENT player is REFUSED `slot_taken` — never overwritten (re-routing requires an explicit rollback first — Story 4.7)');
select is((select (r ->> 'occupant')::bigint from rpc_log where tag = 'alt'), pg_temp.re('TALT', 11),
  'AC1: the refusal names the occupant and the seat — the admin is told WHY, not merely "no"');
select is(pg_temp.comp('TALT', 'losers', 0, 'b'), pg_temp.re('TALT', 11),
  'AC1: the occupied seat is UNCHANGED — the advance did not overwrite the player who was already there');

select is(pg_temp.comp('TALT', 'winners', 8, 'b'), null::bigint,
  'AC1 ⭐⭐ THE WINNER WAS NOT PLACED EITHER, even though their OWN seat was free — a refusal commits NOTHING, so the whole cascade is validated BEFORE any of it is written (a returned refusal does not roll back the caller''s transaction)');
select is(pg_temp.audits('TALT'), 0,
  'AC1: the refusal wrote NO audit row — nothing happened, so nothing is logged as having happened');
select is(pg_temp.msgs('TALT'), 0,
  'AC1/AC3: the refusal emitted NO Broadcast');

-- ════════════════════════════════════════════════════════════════════════════
-- Section K — the champion, and the Story-4.2 cross-story regression (8)
-- ════════════════════════════════════════════════════════════════════════════
-- ⭐ AD-21 (Story 4.4) — SIDE A WINS GAME 1, SO THERE IS NO RESET. gf_order=1's competitor_a is the Winners
-- champion (0 losses); their win makes them champion OUTRIGHT. advance_match's AD-21 conditional crowns them
-- and follows NEITHER reset edge (the reset row, gf_order=2, stays empty). The reset path itself — side B
-- wins and the champion falls out of gf_order=2 — is the flagship of the new 0014 suite.
-- (Seating the GF by hand here is a FIXTURE, not a feature: 4.6 owns the result that gets it there.)
update match
   set competitor_a = pg_temp.re('TADV', 1), competitor_b = pg_temp.re('TADV', 9),
       state = 'resolved', winner_entry = pg_temp.re('TADV', 1)
 where id = pg_temp.mid('TADV', 'grand_final', 0, 1);

insert into rpc_log values
  ('gf', public.advance_match(pg_temp.mid('TADV', 'grand_final', 0, 1), '76561197960287930'));

select is((select (r ->> 'ok')::boolean from rpc_log where tag = 'gf'), true,
  'the Grand Final advances SUCCESSFULLY even though it moves nobody');
select is((select (r ->> 'advanced')::int from rpc_log where tag = 'gf'), 0,
  'advanced = 0: side A (the Winners champion) won game 1, so the AD-21 conditional crowns them and follows NEITHER reset edge — no reset, nobody moves');
select is((select (r ->> 'champion')::bigint from rpc_log where tag = 'gf'), pg_temp.re('TADV', 1),
  '…and the champion is REPORTED, not silently swallowed — a distinct POSITIVE outcome, not a bare zero (the repo''s never-a-silent-no-op convention)');
select is((select final_match_id from tournament where id = pg_temp.tid('TADV')), pg_temp.mid('TADV', 'grand_final', 0, 1),
  'DECISION A: crowning set tournament.final_match_id to the LAST GF row played (here gf_order=1, since side A won outright)');
-- ⭐⭐ THE CHAMPION *DOES* GET A NUDGE, AND THIS ASSERTION IS WHY IT NOW DOES (4.3 code review).
-- The emit used to be gated on `v_hops > 0` alone — a count of PLANNED PLACEMENTS. The Grand Final plans
-- ZERO (it has no outbound edge; its winner IS the champion), so crowning the champion — the single most
-- significant event in a tournament — emitted NOTHING, while an idempotent replay that changed nothing
-- re-planned the same hops and emitted a SECOND nudge. The gate is now `v_hops > 0 OR v_champ is not null`.
-- The old suite asserted the BUG as the desired behaviour, which is how it survived 79 green assertions.
-- (The migration also forbids a second emitter anywhere, so no other layer may announce a champion.)
select is(
  (select count(*)::int from realtime.messages
    where topic = 'tournament:' || pg_temp.tid('TADV')::text
      and (payload ->> 'match_id')::bigint = pg_temp.mid('TADV', 'grand_final', 0, 1)),
  1, 'AC3 ⭐⭐ the CHAMPION advance DOES emit a Broadcast — "when an advance COMMITS, the change propagates to viewers" (AC3 verbatim), and a tournament acquiring a champion is the biggest semantic change there is');
select is(
  (select (payload ->> 'champion')::bigint from realtime.messages
    where topic = 'tournament:' || pg_temp.tid('TADV')::text
      and (payload ->> 'match_id')::bigint = pg_temp.mid('TADV', 'grand_final', 0, 1)),
  pg_temp.re('TADV', 1),
  '…and that Broadcast CARRIES the champion — a viewer learns who won from the nudge''s own payload, not merely that "something changed"');

-- ⭐ THE CROSS-STORY REGRESSION. Every match advanced above was format-LOCKED (the bulk declare froze all
-- 20 playable rows). 0012's `match_format_audited` constraint trigger refuses ANY change to a format
-- column without its authorizing audit row — so if the advance ever touched one, every advance in this
-- suite would have raised P0001. It did not, which is 0012's own comment (":217-219", naming this story)
-- proven rather than trusted. Without this assertion the collision would only surface in Story 4.6.
select ok(
  (select format_locked from match where id = pg_temp.mid('TADV', 'winners', 1)),
  '4.2 regression: the advanced match was format-LOCKED — advance_match works on a frozen match (match_format_audited did NOT fire, because the advance touches no format column)');
select ok(
  (select format = 'mr12' and tie_policy = 'ot_mr3' and format_overridden_at is null
     from match where id = pg_temp.mid('TADV', 'winners', 1)),
  '4.2 regression: …and the advance left every format column exactly as declared — it writes competitors, a winner and a walkover''s state, and NOTHING else');

-- ════════════════════════════════════════════════════════════════════════════
-- Section L — AC1: THE PREDICATE ITSELF, in isolation (3)
-- ════════════════════════════════════════════════════════════════════════════
-- ⚠⚠ THIS SECTION EXISTS BECAUSE MUTATION TESTING FOUND THE SUITE COULD NOT SEE THE PREDICATE AT ALL.
-- Deleting the `WHERE slot IS NULL OR = winner` clause from match_place_competitor — i.e. deleting
-- ACCEPTANCE CRITERION 1 — left every other assertion in this file GREEN. The reason is structural:
-- `advance_match` validates the whole cascade under FOR UPDATE in pass 1, so by the time pass 2 calls the
-- helper the seat is already known to be free (or already ours), and the predicate never gets to decide
-- anything. It is a genuine belt-and-braces backstop — and an UNTESTED one, which is how a backstop
-- quietly stops working.
--
-- It is not dead code: the helper is GRANTED TO service_role, so Stories 4.5/4.6 can call it from inside
-- their own transactions WITHOUT pass 1 in front of it. Its contract is AC1's literal SQL
-- (SOLUTION-DESIGN §7 L357), so AC1 is asserted here directly, on the function that implements it.
set local role service_role;

-- An EMPTY seat accepts the entry. (winners/12 side a is still free — nothing has advanced into it.)
select ok(
  public.match_place_competitor(pg_temp.mid('TALT', 'winners', 12), 'a', pg_temp.re('TALT', 3), false),
  'AC1 (predicate): placing into an EMPTY seat returns true — `slot IS NULL` is the first half of the WHERE');

-- ⭐ THE SAME entry again: a REPLAY. `= winner` is the second half, and it is what makes a double-tap a
-- no-op rather than an error. row_count is still 1, so the caller sees SUCCESS, not a refusal.
select ok(
  public.match_place_competitor(pg_temp.mid('TALT', 'winners', 12), 'a', pg_temp.re('TALT', 3), false),
  'AC1 (predicate) ⭐ re-placing the SAME entry returns TRUE — `OR = winner` is what makes re-applying an advance a no-op instead of a failure');

-- ⭐⭐ A DIFFERENT entry: the seat is held, and the predicate REFUSES. This is the double-route AD-8
-- forbids, caught at the level of the single UPDATE that AC1 actually specifies.
select ok(
  not public.match_place_competitor(pg_temp.mid('TALT', 'winners', 12), 'a', pg_temp.re('TALT', 4), false)
  and pg_temp.comp('TALT', 'winners', 12, 'a') = pg_temp.re('TALT', 3),
  'AC1 (predicate) ⭐⭐ a DIFFERENT entry returns FALSE and does NOT overwrite the occupant — this is the no-double-route guarantee, asserted on the WHERE clause that provides it');

-- ════════════════════════════════════════════════════════════════════════════
-- Section M — AC1: THE PREDICATE MUST GUARD THE *WINNER*, NOT JUST THE SEAT (3)
-- ════════════════════════════════════════════════════════════════════════════
-- ⚠⚠⚠ THE 4.3 CODE REVIEW FOUND THAT SECTION L ABOVE STILL PROVED LESS THAN IT CLAIMED — all three of its
-- calls pass `p_walkover => false`, and `p_walkover => true` was the ONE mode in which the helper was
-- actually unsafe. Found independently by all three review layers and REPRODUCED as service_role:
--
--   The SET writes THREE columns (competitor_a, competitor_b, winner_entry) but the WHERE guarded only the
--   SEAT named by p_side. So crowning arrival Y on the FREE side of a bye node ALREADY WON by X passed the
--   predicate (that seat was empty), silently DEPOSED X, and returned TRUE. `match_winner_is_competitor`
--   did not catch it — Y is a competitor by the time the row settles. And `p_entry => NULL` (the shape a
--   caller trivially produces by passing a bye's non-existent loser) NULLED winner_entry outright and also
--   returned TRUE.
--
-- That is the exact double-route AC1 exists to prevent, performed by the function the story calls
-- "literally the AC". The mutation-testing exercise that produced Section L tested the PREDICATE and missed
-- the GUARD. These three assertions close it, on the function that is granted to service_role and that
-- 4.5/4.6 are explicitly told to call WITHOUT pass 1 in front of it.
--
-- A synthetic walkover node: state='bye', ALREADY WON by seed 1, side b free. (state='bye' is excluded from
-- match_live_requires_locked_format, so it needs no format — 0012:123-126.)
insert into match (tournament_id, bracket, bracket_position, bracket_slot, state,
                   competitor_a, winner_entry,
                   winner_to_bracket, winner_to_slot, winner_to_side)
values (pg_temp.tid('TALT'), 'losers', 'Losers R1 (predicate probe)', 900, 'bye',
        pg_temp.re('TALT', 1), pg_temp.re('TALT', 1),
        'losers', 999, 'a');

-- ⭐⭐ THE RE-CROWN. A DIFFERENT entry, arriving on the FREE seat, asking to be crowned.
select ok(
  not public.match_place_competitor(
        (select id from match where tournament_id = pg_temp.tid('TALT') and bracket = 'losers' and bracket_slot = 900),
        'b', pg_temp.re('TALT', 2), true)
  and (select winner_entry from match
        where tournament_id = pg_temp.tid('TALT') and bracket = 'losers' and bracket_slot = 900)
      = pg_temp.re('TALT', 1),
  'AC1 (predicate) ⭐⭐ crowning a DIFFERENT entry on a walkover ALREADY WON returns FALSE and leaves winner_entry UNTOUCHED — AC1 guards the WINNER, not just the seat. Re-routing a decided match requires an explicit rollback first (AD-8 -> Story 4.7)');

-- The replay half: the SAME winner, re-crowned, is still SUCCESS. Idempotency must survive the new guard —
-- a fix that broke the replay would break AC1 from the other direction.
select ok(
  public.match_place_competitor(
    (select id from match where tournament_id = pg_temp.tid('TALT') and bracket = 'losers' and bracket_slot = 900),
    'a', pg_temp.re('TALT', 1), true)
  and (select winner_entry from match
        where tournament_id = pg_temp.tid('TALT') and bracket = 'losers' and bracket_slot = 900)
      = pg_temp.re('TALT', 1),
  'AC1 (predicate) ⭐ re-crowning the SAME winner is still TRUE and still idempotent — the new winner guard did not break the replay AC1 requires');

-- ⭐ A PLACEMENT OF NOBODY IS NOT A PLACEMENT. This used to return TRUE while ERASING the winner.
select throws_ok(
  format($$ select public.match_place_competitor(%s, 'b', null, true) $$,
         (select id from match where tournament_id = pg_temp.tid('TALT') and bracket = 'losers' and bracket_slot = 900)),
  'P0001', null,
  'AC1 (predicate) ⭐ a NULL entry RAISES instead of silently NULLing winner_entry and reporting success — never a silent no-op, and never a silent erasure (lib/roster.ts:180-182)');

select * from finish();
rollback;
